### ISSUE TITLE
How can we rendered multiple  event in ng- full calender using angular 

### ISSUE THREAD

**Issue by shanabuzar** [fullcalendar/fullcalendar-angular#158]
i have added two hard coded events in event model its showing properly but when i add new event   in events model array dynamically its not showing on calendar
  eventsModel= [
  {
   title:'pakistan day',
   start: '2019-03-23',
   end: '2019-3-023'
 },
 {
   title:'Mjcc holiday',
   start: '2019-03-19',
   end: '2019-03-19'
 }];

    this.eventsModel.push({
          title: result.title,
          start: this.formatDate(result.startDate),
          end: this.formatDate(result.endDate)
        });

**Comment by irustm** [comment]
Try use new array
`this.eventsModel= [];` // new array

---------
i add this function in next relaease
`this.eventsModel.push(`

**Comment by shanabuzar** [comment]
if i will use this  this.eventsModel= [];  it will remove my previous objects and just show the new one

**Comment by irustm** [comment]
yep,
use buffer array, example
this.eventsModel = [...this.eventsModel, {
     title: result.title,
      start: this.formatDate(result.startDate),
      end: this.formatDate(result.endDate)
    }];

**Comment by irustm** [comment]
I close this issue
 If you still have questions, I am ready to answer them
