### ISSUE TITLE
clickButton callback don't work

### ISSUE THREAD

**Issue by gattomannaro** [fullcalendar/fullcalendar-angular#160]
clickButton does not work constantly. I putted a console log in the clickButton method and it is not called every time I click the buttons but just sometimes. Here the code:

`<ng-fullcalendar #fullcalendar [options]="calendarOptions" [eventsModel]="events" (eventClick)="eventClick($event)" (clickButton)="clickButton($event)"></ng-fullcalendar>`

` clickButton(event) {
    if (event.buttonType === 'prev' || event.buttonType === "next") {
      console.log("click");
      this.loadEvents(event.date);
    }
  }`

**Comment by irustm** [comment]
What kind of buttons? Did you change the icons or the css classes?

**Comment by gattomannaro** [comment]
prev and next bottons. I m using the bootstrap plugins and changed the color by css

**Comment by irustm** [comment]
this demo repeats the issue? https://stackblitz.com/edit/ng-fullcalendar2-demo

**Comment by gattomannaro** [comment]
yes

**Comment by irustm** [comment]
![calendar](https://user-images.githubusercontent.com/16316579/55002832-534be300-4fe8-11e9-93ca-c982eb546345.png)
-_-
what you browser?

**Comment by gattomannaro** [comment]
Google Chrome is up to date
Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by irustm** [comment]
I have the same..

**Comment by gattomannaro** [comment]
I setted the method like you but if I click 10 times on a button only 4 times works

**Comment by irustm** [comment]
this old implementation, please see official fullcalendar docs
