### ISSUE TITLE
Is it possible to add right click functionality?

### ISSUE THREAD

**Issue by franklopez** [fullcalendar/fullcalendar-angular#163]
There is a script that adds right click functionality to fullcalendar:

https://github.com/mherrmann/fullcalendar-rightclick

can you integrate-it to ng-fullcalendar?

**Comment by palmurugan** [comment]
Any update on this

**Comment by jolle-c** [comment]
You have to do it yourself.

Here’s one way

        <full-calendar #fullcalendar /... other options.../
          (eventRender)="handleEventRender($event)">
        </full-calendar>


In component
  handleEventRender(e) {
    this.eventService.handleEventRender(e);
  }


In EventService

  handleEventRender(e) {

    e.el.addEventListener('contextmenu', function (ev) {
      ev.preventDefault();
      alert(’Ah, you right clicked!’); // <- replace with own code here
      return false;
    }, false);

  }

Whatever you want to happen on right click is now your responsibility.

HDB
Jolle

**Comment by palmurugan** [comment]
Thank you! @jolle-c

**Comment by irustm** [comment]
This issue has been open for a long time,

Answers, you can see it in the main repositories

https://github.com/fullcalendar/fullcalendar/search?q=right+click&type=Issues

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I believe this existing ticket in the main repo captures this need:
https://github.com/fullcalendar/fullcalendar/issues/2748
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
