### ISSUE TITLE
Problems with plugins

### ISSUE THREAD

**Issue by jemd15** [fullcalendar/fullcalendar-angular#164]
![Captura de Pantalla 2019-03-27 a la(s) 12 04 35](https://user-images.githubusercontent.com/19212855/55087711-47642d80-5089-11e9-8f80-560cdce31d6c.png)
I have problems with some paths of the plugins. Are they changed?

**Comment by irustm** [comment]
no, try `npm install`

and full plugins: https://fullcalendar.io/docs/plugin-index

**Comment by jemd15** [comment]
It doesn't worked. I tried installing with:
npm i @fullcalendar/core
npm i fullcalendar
bur anything worked.

**Comment by irustm** [comment]
try copy and run this repo: 
https://github.com/ng-fullcalendar/ng-fullcalendar2-demo

**Comment by jemd15** [comment]
Did you install the plugins with npm like npm i @fullcalendar/daygrid? Because I was not doing that. Thanks for the help.

**Comment by irustm** [comment]
👍
