### ISSUE TITLE
swipe support with ionic 4?

### ISSUE THREAD

**Issue by jmontana** [fullcalendar/fullcalendar-angular#165]
I want the user to be able to swipe right/left to move backwards/forwards in the calendar. 

I looked at [Issue 120](https://github.com/ng-fullcalendar/ng-fullcalendar/issues/120) but it's only partially working. I have HammerJS installed, and added the (swipe) attribute, but the swipe event only fires if I swipe on the header. If I swipe in the calendar itself, nothing happens.

I'm wondering if fullcalendar is eating the event somehow? 

```
    <div #calendarContainer (swipe)="onSwipe($event)">
        <ng-fullcalendar *ngIf="calendarOptions" #calendar
                         [options]="calendarOptions" (eventClick)="eventTapped($event)"></ng-fullcalendar>
    </div>
```

I tried putting the (swipe) attribute on ng-fullcalendar itself, but that made no difference.

**Comment by irustm** [comment]
ng-fullcalendar is deprecated
try use @fillcalendar/angular with many official API

**Comment by irustm** [comment]
I close this issue,
If you still have questions, I am ready to answer them

**Comment by carlosen14** [comment]
`@fullcalendar/angular` is compatible with ionic 4 /angular 7? i am trying to implement it based on [this demo](https://stackblitz.com/github/fullcalendar/fullcalendar-example-projects/tree/master/angular?file=src%2Fapp%2Fapp.component.ts) yours but does not render anything about calendar..
- [x] installed `@fullcallendar/core@4.3.1` and `@fullcalendar/daygrid@4.3.0`
- [x] did import `@fullcalendar/angular` on main module
- [x] did import syles on global.scss, imported from core, daygrid and list
- [x] did import gridplugin on component
- [x] did use this as a basic example `<full-calendar defaultView="dayGridMonth" [plugins]="calendarPlugins"></full-calendar>`

but shows no grid, no list, nothing.. on html shows  
```html
<full-calendar _ngcontent-c3="" defaultview="dayGridMonth"></full-calendar>
```

**Comment by carlosen14** [comment]
Solved.

imported again on submodule..  

`import { FullCalendarModule } from '@fullcalendar/angular';`

_Commented just to let other people about this case_
