### ISSUE TITLE
initialized callback does not return $event details

### ISSUE THREAD

**Issue by rushenn** [fullcalendar/fullcalendar-angular#167]
I'm trying to get the calendar title when it's loaded using the `initialized` callback.

**HTML**
```
<ng-fullcalendar
        #ucCalendar
        [eventsModel]="events"
        [options]="options"
        (initialized)="initialized($events)"
      >
</ng-fullcalendar>
```

**TS**
```
initialized(model) {
    console.log(model)
}
```

But this callback always returns `undefined`. But I can see other callbacks such as `dateClick`, `eventClick` does returns calendar details.

**Comment by irustm** [comment]
this method just tells you that the calendar has been initialized, don't expect anything from it

**Comment by rushenn** [comment]
Thank you for your prompt reply. Is there a way to print the title when the calendar initialized. Something like 
`console.log(this.fullcalendar.getDate())`

**Comment by irustm** [comment]
After initialize, calendar show current date. Equivalent `new Date()`

**Comment by irustm** [comment]
this old implementation, please see official fullcalendar docs, 
`@Inputs`
