### ISSUE TITLE
Elemets editable only after resize windows browser

### ISSUE THREAD

**Issue by banha-serhii** [fullcalendar/fullcalendar-angular#168]
I need a few calendar display for each user, but when i put this to loop, drag'n'drop work only after resize window browser (or open console)
Has anyone had such a problem?
 Example code here:
https://stackblitz.com/edit/ng-fullcalendar2-demo-dqaf49

**Comment by irustm** [comment]
Try using the usual tabs. mat-tabs overlaps with an additional wrapper

**Comment by irustm** [comment]
Does this happen again with the package @fullcalendar/angular ?

**Comment by irustm** [comment]
I close this issue
 If you still have questions, I am ready to answer them
