### ISSUE TITLE
Events data binding

### ISSUE THREAD

**Issue by GianlucaMaggio** [fullcalendar/fullcalendar-angular#171]
It seems that in Full Calendar doesn't exists any binding option (one way or two ways) with external data.

For example if I use an array of events as event source any change on original data is not reflected on the calendar and any change to calendar events (duration, date, ...) is not reflected on original data. 

Am I doing something wrong or isn't "binding" an expected feature?

**Comment by ultipedro** [comment]
What error are you getting, @GianlucaMaggio ?

**Comment by GianlucaMaggio** [comment]
I have no error but an unexpected behavior. 

> For example if I use an array of events as event source any change on original data is not reflected on the calendar and any change to calendar events (duration, date, ...) is not reflected on original data

**Comment by skaor** [comment]
@GianlucaMaggio are you using spread operator when you update your original data ? Otherwise it will not work because the reference doesn't change.

events = [...events, {newevent}]

**Comment by GianlucaMaggio** [comment]
Ok for one way. But it still not possible to manage data in bi-directional way.

**Comment by krzcho** [comment]
Are you possibly using selectMirror option? I had just similarly looking issue where selectMirror was shadowing newly created events - I guess one needs to disable selectMirror or maybe use calendar.unselect() to hide it after the event is materialized

**Comment by dreadnautxbuddha** [comment]
I'm also encountering this now. Pushing data to the model bound to `[events]` isn't reflecting in the calendar.

**Comment by krzcho** [comment]
What is the type of your variable holding the events? Plain array works for me but Observable is not

**Comment by dreadnautxbuddha** [comment]
I'm using arrays. `[events]="options.events" `  `option` is an object whose `events` attribute is an array. I'm updating the said array with new values

**Comment by arshaw** [comment]
Would someone be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? It's the only way either me or @irustm can start working on a fix

**Comment by arshaw** [comment]
I figured out why this isn't working. I've modified the code for this to be possible in >=4.2.x

There is a performance overhead to looking at deep prop changes within the events, so I'm making this an opt-in setting called `deepChangeDetection`.

I'll write docs and release this really soon

**Comment by dreadnautxbuddha** [comment]
Looking forward to this. Thanks @arshaw!

**Comment by arshaw** [comment]
in [4.2.0](https://github.com/fullcalendar/fullcalendar-angular/releases/tag/v4.2.0), the events data structures are fully reactive.

See https://fullcalendar.io/docs/angular#modifying-properties

**Comment by Pinka30** [comment]
@arshaw I used the deepChangeDetection in my code as per your example, but no luck.

below is my code,
calendarOptions: CalendarOptions = {
    initialView: 'dayGridMonth',
    showNonCurrentDates: false,
    fixedWeekCount: false,
    events: this.calendarEvents
  };

depending on an option selected by user, I need to change/update the events list, so in the if condition I am reassigning events with another events list array, but the change is not reflecting.

if(this.timeline_val == 'SBIR'){    
        this.calendarOptions = {
        initialView: 'dayGridMonth',
        showNonCurrentDates: false,
        fixedWeekCount: false,
        events: this.calendarEvents2
      };

calendarEvents2 is not reflecting.

What can be done here?
