### ISSUE TITLE
FullCalendar options example

### ISSUE THREAD

**Issue by pselis** [fullcalendar/fullcalendar-angular#177]
Hi there
Thanks for the beautiful work!.

I just started using this component but I don't understand how to use FullCalendar's options like:
columnHeaderFormat , columnHeaderText or columnHeaderHtml
Thanks for helping

**Comment by irustm** [comment]
Hi!
see exapmle:
https://stackblitz.com/edit/angular-wmaddr?file=src%2Fapp%2Fapp.component.ts
```
    columnHeaderHtml: () => {
          return '<b>Friday!</b>';
    },
```

and please read docs https://fullcalendar.io/docs/columnHeaderHtml

**Comment by mniak** [comment]
The example link is broken

**Comment by irustm** [comment]
@mniak 
https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by irustm** [comment]
I close this issue
 If you still have questions, I am ready to answer them
