### ISSUE TITLE
Double click on date

### ISSUE THREAD

**Issue by gattomannaro** [fullcalendar/fullcalendar-angular#180]
Hi, is it possible to insert the double click on a singe date?

**Comment by irustm** [comment]
https://stackblitz.com/edit/angular-wmaddr?file=src%2Fapp%2Fapp.component.ts
example:
```
dayRender(ev){
    ev.el.addEventListener('dblclick', () => {
       alert('double click!');
    });
  }
```

**Comment by gattomannaro** [comment]
I tried it, it does not work cause the are other components (i.e. if on the row there are events) over the element.

**Comment by irustm** [comment]
Please try to reproduce your issue on stackblitz so that I can understand what's going on

**Comment by gattomannaro** [comment]
https://stackblitz.com/edit/angular-7oygbt?file=src%2Fapp%2Fapp.component.ts
if you try to double click on 10th april the listener is not triggered, cause the event component is present, hidden, in the whole row.

**Comment by irustm** [comment]
I'm sorry, fullcalendar does not currently support dblclick. that was just my guess for the solution to your issue. 
Try asking this in the main repository.

**Comment by irustm** [comment]
I close this issue
 If you still have questions, I am ready to answer them
