### ISSUE TITLE
typescript compile errors while import resource-timeline

### ISSUE THREAD

**Issue by ajaxsys** [fullcalendar/fullcalendar-angular#181]
### Bug Reports
Try import `'@fullcalendar/resource-timeline';` and get compile errors.

![type_errors](https://user-images.githubusercontent.com/627262/56492958-617a1a00-6528-11e9-9015-bdc4476cce01.png)

Here is my dependencies:

```

  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@fullcalendar/core": "^4.0.2",
    "@fullcalendar/daygrid": "^4.0.1",
    "@fullcalendar/interaction": "^4.0.2",
    "@fullcalendar/angular": "^4.0.2",
    "@fullcalendar/resource-timeline": "^4.0.2",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  }

```

Here is 'ng build' errors

> ERROR in node_modules/@fullcalendar/core/main.d.ts(2760,14): error TS2484: Export declaration conflicts with
> exported declaration of 'OptionsInput'.
> node_modules/@fullcalendar/core/main.d.ts(2761,26): error TS2484: Export declaration conflicts with exported
> declaration of 'EventDef'.
> node_modules/@fullcalendar/core/main.d.ts(2788,14): error TS2484: Export declaration conflicts with exported
> declaration of 'Calendar'.
> node_modules/@fullcalendar/core/main.d.ts(2795,24): error TS2484: Export declaration conflicts with exported
> declaration of 'DateSpanApi'.
> node_modules/@fullcalendar/core/main.d.ts(2795,37): error TS2484: Export declaration conflicts with exported
> declaration of 'DatePointApi'.
> node_modules/@fullcalendar/core/main.d.ts(2815,35): error TS2484: Export declaration conflicts with exported
> declaration of 'CalendarState'.
> node_modules/@fullcalendar/core/main.d.ts(2824,14): error TS2484: Export declaration conflicts with exported
> declaration of 'EventMutation'.
> node_modules/@fullcalendar/core/main.d.ts(2826,14): error TS2484: Export declaration conflicts with exported
> declaration of 'EventApi'.
> node_modules/@fullcalendar/resource-common/main.d.ts(350,9): error TS2416: Property 'getKeysForEventDef' in t
> ype 'ResourceSplitter' is not assignable to the same property in base type 'Splitter<SplittableResourceProps>
> '.
>   Type '(eventDef: import("@fullcalendar/core").EventDef) => string[]' is not assignable to type '(eventDef:
> import("@fullcalendar/core/structs/event").EventDef) => string[]'.
>     Types of parameters 'eventDef' and 'eventDef' are incompatible.
>       Type 'import("@fullcalendar/core/structs/event").EventDef' is not assignable to type 'import("@fullcale
> ndar/core").EventDef'.
>         Property 'resourceIds' is missing in type 'EventDef'.
> node_modules/@fullcalendar/resource-common/main.d.ts(486,9): error TS2416: Property 'getKeysForEventDef' in t
> ype 'VResourceSplitter' is not assignable to the same property in base type 'Splitter<VResourceProps>'.
>   Type '(eventDef: import("@fullcalendar/core").EventDef) => string[]' is not assignable to type '(eventDef:
> import("@fullcalendar/core/structs/event").EventDef) => string[]'.
>     Types of parameters 'eventDef' and 'eventDef' are incompatible.
>       Type 'import("@fullcalendar/core/structs/event").EventDef' is not assignable to type 'import("@fullcale
> ndar/core").EventDef'.
> projects/fullcalendar/src/lib/fullcalendar.component.ts(40,25): error TS2693: 'Calendar' only refers to a typ
> e, but is being used as a value here.
> projects/fullcalendar/src/lib/fullcalendar.component.ts(41,19): error TS2339: Property 'render' does not exis
> t on type 'Calendar'.
> projects/fullcalendar/src/lib/fullcalendar.component.ts(72,21): error TS2339: Property 'setOptions' does not
> exist on type 'Calendar'.
> projects/fullcalendar/src/lib/fullcalendar.component.ts(77,19): error TS2339: Property 'destroy' does not exi
> st on type 'Calendar'.
> src/app/app.component.ts(19,7): error TS2322: Type '{ editable: boolean; customButtons: { myCustomButton: { t
> ext: string; click: () => void; }; }; header: { left: string; center: string; right: string; }; plugins: Plug
> inDef[]; }' is not assignable to type 'OptionsInput'.
>   Object literal may only specify known properties, and 'editable' does not exist in type 'OptionsInput'.
> src/app/app.component.ts(47,18): error TS2339: Property 'header' does not exist on type 'OptionsInput'.
>

**Comment by irustm** [comment]
Try not to use the OptionInput interface, 
because the options aren't transferred in one object. If this is not an acceptable solution for you, try writing in the main repository

**Comment by vnelis** [comment]
I had the same issue. Is there any fix?

**Comment by ejmason101** [comment]
Maybe related to https://github.com/fullcalendar/fullcalendar/issues/4579

**Comment by dkrusenstrahle** [comment]
Same issue here (and even on resourceTimeGridPlugin). Any solution?

**Comment by MVMurrell** [comment]
You must change your Typescript version to ~3.2.2, I tried changing it to the latest version and it did not work. This version seems to be key. npm install after of course

**Comment by irustm** [comment]
I close this issue
 If you still have questions, I am ready to answer them

**Comment by Ruben-softour** [comment]
> I close this issue
> If you still have questions, I am ready to answer them

I have the same problem ): 
If you know how to resolve this fix, Could you post it please?

Thank you in advance for your help :)

**Comment by ridoyraihan** [comment]
Changing my typescript version fix this issue but gives  "Build:Duplicate identifier 'IteratorResult'." error.
