### ISSUE TITLE
dayRender not working like resourceRender

### ISSUE THREAD

**Issue by JeroenKurvink** [fullcalendar/fullcalendar-angular#182]
Im using @fullcalendar/angular and '@fullcalendar/core'. And dayRender is not working for me. it doesnt matter if I console.log(event) or try to manipulate te object by giving it a new backgroundcolor. 
eventClick, datesRender and resourcerender ARE working like I would expect dayRender to work.

```
<full-calendar 
.......
[events]="events"
`(eventClick)="eventClick($event)"`
(datesRender)="datesRender($event)"
(dayRender)="dayRender($event)"
(resourceRender)="resourceRender($event)"
>
</full-calendar>
```

```
dayRender(model: any) {
    model.el.style.backgroundColor = 'blue';
    console.log(model);
}

 resourceRender(model: any) {
   model.el.style.backgroundColor = 'blue';
   console.log(model);
}
```
I'm using the resourceTimelinePlugin
`plugins: [bootstrap, resourceTimelinePlugin, interactionPlugin]`

**Comment by irustm** [comment]
To solve the issue, please add an example of your code to this demo: https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by JeroenKurvink** [comment]
Hello irustm, Thanks for helping

I altered your example to show my problem. In my example I did manage to get dayRender to call for each day (7 times), but I expected it to call every day for each resource.

https://stackblitz.com/edit/fullcalendar-angular-demo-ewolot

**Comment by JeroenKurvink** [comment]
I realised that this is not possible with fullcalender

**Comment by therichpostajay** [comment]
Try this:
dayCellContent : { html: 'Your Text' },

This helps to add html like dayrender.

THANKS

**Comment by zachbresler21** [comment]
But dayCellContent only allows you to add HTML in daygridview not resourcetimelineweek view
How would you be able to add HTML to each cell of the parent resource for each date in resourcetimelineweek view?

**Comment by amirul1000** [comment]
ngAfterViewInit(){
    // Your CSS as text
    var styles =`
    .fc td, .fc th {
      vertical-align: top;
      padding: 0;
      height: 100px;
    }
    a{
      color:#3d1cba;
    }
    `


    let styleSheet = document.createElement("style");
    styleSheet.innerText = styles;
    document.head.appendChild(styleSheet);


    let arrTD = document.querySelectorAll('td.fc-timeline-slot');
    let arrTR= document.querySelectorAll('td.fc-timeline-lane.fc-resource');
    let arrInject= document.querySelectorAll('td.fc-timeline-lane.fc-resource>div.fc-timeline-lane-frame');
    console.log(arrTR);

    let k=-1;
    arrTR.forEach(eachTR => {
        let i=1;
        let str = '';
        k++;

        let data_resource_id= eachTR.getAttribute('data-resource-id');
        console.log(data_resource_id);

        arrTD.forEach(eachTD => {          
            let  k=100*(i-1);
            i=i+1;
            let data_date= eachTD.getAttribute('data-date');
            console.log(data_date);

            let data_resource_id= eachTR.getAttribute('data-resource-id'); 
            console.log(data_resource_id);

            str = str + '<span data-date="'+data_date+'" data-resource-id="'+data_resource_id+'" class="plus_icon" style="position:relative;top: 0px; left: '+k+'px !important;width:500px;height:500px;z-index:3;-moz-border-radius:100px;border:1px  solid #ddd;-moz-box-shadow: 0px 0px 8px  #fff;">+</span>';          
      
         
      });
        arrInject[k].innerHTML=str;

    });

    
    let elementList = this.elRef.nativeElement.querySelectorAll('span.plus_icon');
    for(let i=0;i<elementList.length;i++){   
     elementList[i].addEventListener('click', this.plusClick.bind(this));
    }
}

**Comment by amirul1000** [comment]
![image](https://user-images.githubusercontent.com/5242039/162121928-c7a91ba6-c8a8-4d32-a41d-829906939114.png)
