### ISSUE TITLE
Locales work for the calendar but not the header button

### ISSUE THREAD

**Issue by dragonetty22** [fullcalendar/fullcalendar-angular#183]
I am using Angular 7 and although the 'Locale' works for the calendar, the buttons are not translated.
I used the property 'buttonText' to fix it temporarily.

**Comment by irustm** [comment]
Maybe you didn't plug in the right plugin, look at this demo please: https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by rinichi** [comment]
Same issue here on Angular
    
![image](https://user-images.githubusercontent.com/49209426/57831762-4cef1180-77b6-11e9-94db-f8cd5b4f7952.png)

I can't modify `locale` and `firstDay` , the others options works

**Comment by raso03031983** [comment]
> Estou usando o Angular 7 e, embora o 'Locale' funcione para o calendário, os botões não são traduzidos. 
> Eu usei a propriedade 'buttonText' para corrigi-lo temporariamente.

Como você conseguiu colocar o locale pra funcionar. Estou tendo muito trabalho e não tenho nenhuma evolução

**Comment by raso03031983** [comment]
How did you get the locale to work? I'm having a lot of work and I do not have any evolution

**Comment by reinaldoalbernaz** [comment]
I was using [locale]="pt-br", I just removed the brackets and it worked, locale="pt-br"
