### ISSUE TITLE
 Event Dragging no move

### ISSUE THREAD

**Issue by dragonetty22** [fullcalendar/fullcalendar-angular#184]
I am using Angular 7. I can not drag the events. The 'editable' property of the calendar is true, The 'editable' property of the event is true. But the event does not move.

**Comment by irustm** [comment]
Maybe you didn't plug in the right plugin, look at this demo please:  https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by RyanChouTaiwanTaipei** [comment]
Is there a way to confirm the trigger?
I confirm have to set **interactionPlugin**.
but, I can not drag the events too.

**Comment by isa424** [comment]
Can confirm that it does not work on ^4.1. Reverted back to 4.0.2-beta

**Comment by simhib** [comment]
Also revert back to 4.0.2-beta. After the upgrade broken any drag ability of the calendar control.

**Comment by eveve86** [comment]
I was not able to make draggable work (events inside the same calendar) with version 4.3.1
Is it possible that  I am doing something wrong or it is just not working? (I set editable on the calendar level and also on the event level), I do not know if anything else is missing.

**Comment by frankps** [comment]
I'm working with version 4.3 and dragging still doesn't work.

**Comment by ShaunBrassell** [comment]
4.3 worked for me, I just did not download and include the interactionPLugin correctly:

import interactionPlugin from '@fullcalendar/interaction'; 
calendarPlugins = [dayGridPlugin, interactionPlugin];

  <full-calendar defaultView="dayGridMonth" [weekends]="true" [events]="calendarEvents" [fixedWeekCount]="false" [height]="600" [plugins]="calendarPlugins" [editable]="true"></full-calendar>

**Comment by irustm** [comment]
Sorry it took me a long time to answer, I think you've got the plugin wrong, please look at the examples  https://stackblitz.com/edit/fullcalendar-angular-demo and comment @ShaunBrassell . If it doesn't work, please write to me.

**Comment by codealvarez** [comment]
> Maybe you didn't plug in the right plugin, look at this demo please: https://stackblitz.com/edit/fullcalendar-angular-demo

It works, nice, thank you
