### ISSUE TITLE
Events with html in title

### ISSUE THREAD

**Issue by M-Blobby** [fullcalendar/fullcalendar-angular#185]
Hello,

I'm working with fullcalendar-angular 4.0.2 and I'm searching how to display an icon, or any html template, inside the title attribute.

I read this ticket https://github.com/fullcalendar/fullcalendar-angular/issues/121, but $event.detail is undefined.

**Comment by irustm** [comment]
Hi! try use eventRender($event)

**Comment by M-Blobby** [comment]
Hi @irustm ,

Thanks for your help, eventRender do the job :)

**Comment by MiguelGonzalezAravena** [comment]
> Hi @irustm ,
> 
> Thanks for your help, it works with eventRender :)

How did you get it?

**Comment by M-Blobby** [comment]
Hi @MiguelGonzalezAravena ,

In my template with the callback "eventRender" :
```html
<full-calendar #calendar
    ........
    (eventRender)="eventRender($event)">
  </full-calendar>
```

And in my component :
```javascript
eventRender(model: any): void {
    // model.el.className += ......
    model.el.innerHTML += '<span class="icon-close"></span>';
  }
```
