### ISSUE TITLE
Prev and Next

### ISSUE THREAD

**Issue by M-Blobby** [fullcalendar/fullcalendar-angular#186]
Hello,

I'm searching how to hire methods with the buttons "prev" and "next" in the header, but without success (v4.1.0) ...
I tried with the callback prev(), next(), and clickButtons() but nothing happened (and I don't see them in the Output() list of this project).

Someone has any clue about that ?

Thank you for your help :)

**Comment by M-Blobby** [comment]
I resolved my problem with the Output() datesRender and the return $el.view.activeEnd and $el.view.activeStart.

**Comment by Cafnio** [comment]
Had the same issue as you, fixed using (datesRender)="eventClick($event)".

you can also get (dayRender)="eventClick($event)". which returns you all the days for that month

**Comment by irustm** [comment]
I close this issue
 If you still have questions, I am ready to answer them
