### ISSUE TITLE
External events (Angular version)

### ISSUE THREAD

**Issue by anakin59490** [fullcalendar/fullcalendar-angular#192]
Hi, 

As you know ng-fullcalendar is now deprecated :  
https://www.npmjs.com/package/ng-fullcalendar

So is-it possible to "convert" https://fullcalendar.io/docs/external-dragging in Angular version

I have defined calendar in HTML file:  

`<div *ngIf="options">
   <full-calendar
     #calendar
   [allDaySlot]=options.allDaySlot
   [customButtons]="options.customButtons"
   [defaultView]="options.defaultView"
   [displayEventEnd]="options.displayEventEnd"
                                        [droppable]="options.droppable"
                                        [editable]="options.editable"
                                        [events]=events
                                        [header]="options.header"
                                        [height]="options.height"
                                        [locale]="options.locale"
                                        [plugins]="calendarPlugins"
                                        [slotDuration]="options.slotDuration"
                                        [slotEventOverlap]="options.slotEventOverlap"
                                        (dateClick)="dateClick($event)"
                                        (eventClick)="eventClick($event)"
                                        (eventDragStop)="dateClick($event)"
                                        (eventReceive)="eventReceive($event.detail)"
                                    ></full-calendar>
                                </div>`

I have defined the list of the elements i want to "drag & drop" on the calendar (html)
` <tbody >
                            <tr *ngFor="let ticket of ticketList">
                                <td style="width: 10%">
                                    <button class="btn btn-danger btn-round btn-fab btn-fab-mini">
                                        <i (click)="deleteTicket(ticket.ticketDTO.idaiticket)" class="material-icons" title="Supprimer">delete</i>
                                    </button>
                                </td>
                                <td #customevents class='fc-event' [attr.data-idaiticket]="ticket.ticketDTO.idaiticket" data-duration='02:00'>TICKET N° {{ticket.ticketDTO.idaiticket}}</td>
                                <td><b>{{ticket.siteDTO.libelle}}</b></td>
                                <td >{{ticket.ticketDTO.message}}</td>
                            </tr>
                            </tbody>`

And in TS file : 

` @ViewChildren('customevents') customevents: QueryList<any>;`
`@ViewChild('calendar') calendarComponent: FullCalendarComponent; // the #calendar in the template`
 ` options: OptionsInput;`
 `calendarPlugins = [dayGridPlugin, timeGrigPlugin, interactionPlugin];`
 ` events: Intervention [] = [];`
 `ticketList: Intervention [] = [];`

`this.options = {
            defaultDate: today,
            allDaySlot: false,
            defaultView: 'timeGridWeek',
            displayEventEnd: true,
            editable: true,
            locale: frLocale ,
            height: 600,
            slotDuration : '00:15:00',
            slotEventOverlap: false,
            droppable: true,
            // eventLimit: false,
            customButtons: {
                myCustomButton: {
                    text: 'Valider',
                    click: function () {
                        alert('clicked the custom button!');
                    }
                }
            },
            header: {
                left: 'prev, next, today, myCustomButton',
                center: 'title',
                right: 'dayGridMonth, timeGridWeek, timeGridDay '
            }
        };`

But I dont'succeed to make element "draggable"...

Thank's in advance

**Comment by irustm** [comment]
see please demo with External events:

https://stackblitz.com/edit/fullcalendar-angular-demo?file=src%2Fapp%2Fapp.component.html
and 

https://github.com/ng-fullcalendar/fullcalendar-angular-demo

**Comment by anakin59490** [comment]
Thank's a lot , it works nice.

**Comment by calldeludo** [comment]
Hello, i checked the example and the demo that you provided... but i am still trying to find how can i catch the event when i click on next or prev, or today... there is any method to get these events?

**Comment by chiraggmodi** [comment]
is it possible to style the grabed event?

**Comment by jolle-c** [comment]
Yes

**Comment by nehayargal** [comment]
> Yes
> […](#)
> 25 nov. 2019 kl. 11:05 skrev Chirag Modi ***@***.***>: is it possible to style the grabed event? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Could  you please provide some details on that?

**Comment by paninee** [comment]
Is it possible to drag External Event displayed from separate sharable module? 
I have `external-events.module.ts` and `calendar-preview.module.ts`

in external-events.component.ts, I have the code for the draggable elements. 
```
<div #external>
  <p>
    <strong>Draggable Events</strong>
  </p>
  <div class='fc-event'>My Event 1</div>
  <div class='fc-event'>My Event 2</div>
  <div class='fc-event'>My Event 3</div>
  <div class='fc-event'>My Event 4</div>
  <div class='fc-event'>My Event 5</div>
</div>
```

And in my calendar-preview.component.ts
```
<full-calendar
  [defaultView]="defaultView"
  [header]="calendarOptions.header"
  [plugins]="calendarOptions.plugins"
  [events]="events"
  [editable]="calendarOptions.editable"
  [droppable]="calendarOptions.droppable"
  [displayEventTime]="calendarOptions.displayEventTime"
  (datesRender)="datesRender($event)">
</full-calendar>
```

Now these 2 sharable modules are imported in my main routing module/page. Let's say I have route `http://mywebsite.com/schedules`. 

And in this route I have schedule.component.ts looks like


```
<app-external-events></app-external-events>
<app-calendar-preview></app-calendar-preview>
```

Question is. Is  there a way to drag elements from `app-external-events` component to `app-calendar-preview`?
