### ISSUE TITLE
Issue in drag functionality when using full calender in page as well as popup

### ISSUE THREAD

**Issue by dhavalsolanki** [fullcalendar/fullcalendar-angular#194]
Hello I am using full calendar in my page as well as popup which is opened from the same page. By drag functionality is not working in my page.
In my page i have disabled editing and in my popup i have enabled editing but drag functionality is not working.
![Error](https://user-images.githubusercontent.com/5657449/57827340-9c3c3e80-77c4-11e9-92e7-ee7b159e523b.PNG)

**Comment by irustm** [comment]
maybe your modal window overlaps, try without modal window

**Comment by irustm** [comment]
Please tell me if this answer solved your issue

**Comment by irustm** [comment]
i'm close this issue, if you find better solved tell me please
