### ISSUE TITLE
FullCalendar not rendering properly

### ISSUE THREAD

**Issue by Andrespvzla** [fullcalendar/fullcalendar-angular#195]
Im building an Ionic 4 app with FullCalendar and i have something like this:

![image](https://user-images.githubusercontent.com/39382388/57827947-8c4a3d80-7777-11e9-955c-9e7d2860ece1.png)

If you see FullCalendar is not rendering properly but if i click on next or prev buttons it renders

![image](https://user-images.githubusercontent.com/39382388/57828007-d3383300-7777-11e9-9f05-2000a97e6b2b.png)

What am I doing wrong?

**Comment by Andrespvzla** [comment]
I got this on my .ts and got a button on my html to use the method render(); and when i click it renders good

`  @ViewChild('calendar') calendarComponent: FullCalendarComponent;

  calendarPlugins = [dayGridPlugin];

  render() {
    let calendario = this.calendarComponent.getApi();
    calendario.render();
  }`

**Comment by irustm** [comment]
are there any errors in the console?

**Comment by Andrespvzla** [comment]
No errors just this

![image](https://user-images.githubusercontent.com/39382388/58057210-202e5780-7b32-11e9-978c-128ec9900890.png)

**Comment by mtraut** [comment]
The same problem with me:

* Ionic 4
* Angular 7

Having <full-calendar> in <ion-content> does not trigger rendering upon initial display. When resizing, the calendar shows up.

Usual workarounds (setTimeout) do not succeed.

**Comment by mtraut** [comment]
This seems to be related with Ionic-4 - omitting <ion-content> and directly using a <div style="overflow: auto"> renders correctly.

**Comment by chriscarreau** [comment]
Hello I have the same issue with an Angular 7 project, it doesn't show up when first loading the page, but if I resize the page or actually do anything that forces a re-render (like clicking next/prev) it then shows up. I am NOT using Ionic though, so I'm pretty sure this is not a Ionic only thing

**Comment by Cafnio** [comment]
Also had this problem on Angular projects. Fixed using the following workaround in scss

/deep/ .fc-scroller.fc-day-grid-container {
  overflow: auto !important;
  height: auto !important;
}

When it loads, the overflow is set as hidden and height as 0. That's why it doesn't show nothing (it renders but it's hidden)

**Comment by irustm** [comment]
I close this issue, 
I hope it's just an ionic problem.
If you still have questions, I am ready to answer them

**Comment by jdnichollsc** [comment]
@pioneersingh321 wowww awesome, thanks!

**Comment by punjabideveloper** [comment]
contentHeight="auto" worked for me.

**Comment by rajeshwarpatlolla** [comment]
This one is working for me.

```
ngOnInit() {
    setTimeout( function() {
        window.dispatchEvent(new Event('resize'))
    }, 1)
}
```

**Comment by GeekChanaa** [comment]
the answer by @rajeshwarpatlolla worked for me. But I didn't quite understand why it's not rendering before resizing the window (I'm working with angular)

**Comment by davorcosic** [comment]
You can also get a reference to the FullCalendarComponent by using ViewChild and afterwards update the size of the component in ViewWillEnter Ionic lifecycle hook: 

```
export class CalendarComponent implements ViewWillEnter {

  @ViewChild(FullCalendarComponent) calendar: FullCalendarComponent;

  public ionViewWillEnter(): void {
    this.calendar.getApi().updateSize();
  }
}

**Comment by horsebuzz** [comment]
None of the above HAC worked for me. I am on latest version of Ionic and Angular.

Any other suggestions?

**Comment by xespinos** [comment]
Still having the same problem with Angular 12. Tried all the above options and no one worked. Anything else to try?

**Comment by Arathy-sivan** [comment]
I am facing the same problem, the full calendar is not displaying..
my html is, 
 <p-fullcalendar  [events]="events"
         [options] ="calendarOptions"
         [defaultView]="dayGridMonth"
         [plugins]="calendarPlugins"
         ></p-fullcalendar> 
       
     I didn't get anything in the screen, can you please help me to solve this problem??

**Comment by S0f0s** [comment]
contentHeight="auto" is working in React too! 
Thank you
