### ISSUE TITLE
How do I correctly use a function as an event source?

### ISSUE THREAD

**Issue by dreadnautxbuddha** [fullcalendar/fullcalendar-angular#196]
I'm not sure if this is a bug, or an intended functionality but whenever I access my method that I have indicated in the `[events]` property of `<full-calendar></full-calendar>`, calling `this`  returns null, therefore, I cannot use my services.

![Screenshot from 2019-05-16 13-22-05](https://user-images.githubusercontent.com/24476736/57828433-13320100-77de-11e9-976c-5c0ec096b356.png)

![Screenshot from 2019-05-16 13-25-48](https://user-images.githubusercontent.com/24476736/57828452-28a72b00-77de-11e9-9d67-fe65e12fab19.png)

Am I doing something wrong?

**Comment by irustm** [comment]
`[events]` it's array of event
example:
https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by dreadnautxbuddha** [comment]
So currently, there's no support for functions?

**Comment by irustm** [comment]
Try use eventsource: https://github.com/fullcalendar/fullcalendar-angular/blob/master/projects/fullcalendar/src/lib/fullcalendar-options.ts#L95

**Comment by dreadnautxbuddha** [comment]
Sure, i'll try it sometime. I will open another inquiry in a separate thread if it doesn't work. Thanks @irustm

**Comment by arshaw** [comment]
@dreadnautxbuddha, I understand your problem. You care about the `this` value of the callback.

I know you don't like the fact that it's `null`, but what value were you hoping it would be?

**Comment by dreadnautxbuddha** [comment]
Hi @arshaw , I was hoping that instead of `null`, that it should be the context of the current component.
This is so that I could call various services, methods, etc. within my component

**Comment by Neddd** [comment]
This works. I personally like the first example

```
export class YourComponent implements OnInit {
  eventSources: Array<any> = [];

  constructor(){}

  ngOnInit() {
    this.eventSources = [ this.fetchEvents( this ) ]
  }

  fetchEvents( _this ) {
      return ( fetchInfo, successCallback, failureCallback ) => {
        _this.someAsyncCallToServer( fetchInfo ).then( ( events ) => {
          successCallback( event );
        } ).catch( ( error ) => {
          failureCallback( error );
        } );
      };
  }
}
```
OR
```
export class YourComponent implements OnInit {
  eventSources: Array<any> = [];

  constructor(){}

  ngOnInit() {
    this.eventSources = [ this.fetchEvents.bind(this) ]
  }

  fetchEvents( fetchInfo, successCallback, failureCallback) {
        this.someAsyncCallToServer( fetchInfo ).then( ( events ) => {
          successCallback( event );
        } ).catch( ( error ) => {
          failureCallback( error );
        } );
  }
}
```

Then:
`<full-calendar #calendar [plugins]="plugins" [eventSources]="eventSources" ></full-calendar>`

Pieced together from: https://fullcalendar.io/docs/events-function

**Comment by ngardner** [comment]
Thank you @Neddd exactly what I needed as well
