### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by dneuschaefer-rube** [fullcalendar/fullcalendar-angular#197]
I compiled a list of missing properties from `OptionsInput` in the core repo ([#4690](https://github.com/fullcalendar/fullcalendar/issues/4690)), and most of these are also missing here:

- `allDayHtml` (entirely undocumented, so this might be by choice)
- `eventDragMinDistance`
- `eventResourceEditable`
- `eventSourceFailure`
- `eventSourceSuccess`
- `forceEventDuration`
- `progressiveEventRendering`
- `selectLongPressDelay`
- `timeZoneParam`
- `titleRangeSeparator`
- `refetchResourcesOnNavigate` (scheduler)

**Comment by irustm** [comment]
PR welcome:) 
https://github.com/fullcalendar/fullcalendar-angular/blob/master/projects/fullcalendar/src/lib/fullcalendar-options.ts#L6-L8

**Comment by arshaw** [comment]
fixed in the latest master. will release soon

**Comment by arshaw** [comment]
missing props have been added in 4.2.0

https://github.com/fullcalendar/fullcalendar-angular/releases/tag/v4.2.0
