### ISSUE TITLE
Component bootstrap: Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by fabdeceglia** [fullcalendar/fullcalendar-angular#198]
Hello everyone,

i successully integrated the latest version of Angular Fullcalendar (at this time **4.1.0**) in my Angular 7 application. 
Everything is working, except for the fact that at the startup of the application this error is always shown in the console:

`Uncaught TypeError: Cannot read property 'fn' of undefined
    at Object.<anonymous> (fullcalendar.min.js:6)
    at e (fullcalendar.min.js:6)
    at Object.<anonymous> (fullcalendar.min.js:8)
    at e (fullcalendar.min.js:6)
    at Object.<anonymous> (fullcalendar.min.js:6)
    at e (fullcalendar.min.js:6)
    at Object.<anonymous> (fullcalendar.min.js:12)
    at e (fullcalendar.min.js:6)
    at fullcalendar.min.js:6
    at fullcalendar.min.js:6`

Is it something related to the dependency import order?
Despite the error, everything is working fine.

Let me know if i can add other details.

Thank you.

**Comment by irustm** [comment]
Please, add your error code to https://stackblitz.com/

**Comment by fabdeceglia** [comment]
> Please, add your error code to https://stackblitz.com/

Hi, i tried but i cannot reproduce it on stackblitz.

**Comment by fabdeceglia** [comment]
Ok guys, i solved it|

In my application skeleton there is a proper section with the import order of the third party libraries.
I need to import moment library **before** jquery.

Now the error is gone.
Thanks guys for the reply, i will close the issue ;)
