### ISSUE TITLE
Angular Universal: Element is not defined

### ISSUE THREAD

**Issue by martinsiden** [fullcalendar/fullcalendar-angular#199]
Hi there!

Thank you for this fantastic Angular wrapper of Fullcalendar. 

Unfortunately it doesn't seem to build with Angular Universal. Here's a repo that reproduces the error:

[https://github.com/martinsiden/fullcalendar-universal](https://github.com/martinsiden/fullcalendar-universal)

Here's the steps I took when creating the repo:

Fire up new Angular CLI project:

    ng new fullcalendar-universal

Add Angular Universal:

    ng add @nguniversal/express-engine --clientProject fullcalendar-universal

Test run without Fullcalendar:

    npm run build:ssr && npm run serve:ssr

Install Fullcalendar:

    npm i --save @fullcalendar/angular @fullcalendar/core @fullcalendar/daygrid

Adding Fullcalendar to `app.module.ts`:

    imports: [
      ...
      FullCalendarModule
    ]

Adding fullcalendar to `app.component.html` and passing in `dayGridPlugin` to it.

Adding CSS to `angular.json`:

    "styles": [
        "node_modules/@fullcalendar/core/main.css",
        "node_modules/@fullcalendar/daygrid/main.css",
        "src/styles.css"
    ],

Starting "normally" with:

    npm start

But running via Universal with:

    npm run build:ssr && npm run serve:ssr

fails with:

    /workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:133941
        var matchesMethod = Element.prototype.matches ||
                        ^

    ReferenceError: Element is not defined
    at /workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:133941:25
    at /workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:133842:13
    at Object.<anonymous> (/workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:133844:2)
    at __webpack_require__ (/workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:20:30)
    at /workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:142649:30
    at Object.<anonymous> (/workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:142651:2)
    at __webpack_require__ (/workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:20:30)
    at Object.@fullcalendar/daygrid (/workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:133311:18)
    at __webpack_require__ (/workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:132835:30)
    at Module../src/app/app.component.ts (/workspace/fullcalendar-universal/fullcalendar-universal/dist/server.js:133017:79)

**Comment by irustm** [comment]
run fullcalendar without server
example:
```ts
    private isServer: boolean;

    constructor(
        private tstate: TransferState,
        @Inject(PLATFORM_ID) platformId
    ) {
        this.isServer = isPlatformServer(platformId);
    }
```

**Comment by martinsiden** [comment]
And then just `<full-calendar *ngIf="!isServer"`?

I get the exact same error doing that.

**Comment by irustm** [comment]
I'll try to reproduce it in your repository...

**Comment by martinsiden** [comment]
Thanks!

**Comment by irustm** [comment]
I understand your problem.
This is a problem with third-party modules when working with ssr. You need to additionally connect `domino`.
Try use this starter: https://github.com/Angular-RU/angular-universal-starter/
It takes into account most of the popular issues

**Comment by martinsiden** [comment]
Well, I have quite a large project where fullcalendar is a "late addition", so I can't just use the starter as is, but thanks for pointing out the problem. I'm gonna learn about domino first and then try to implement it. 

I think it's very strange that the official universal documentation doesn't even touch on this subject at all. Anyways, since it's not an issue with Fullcalendar itself let's just close this. 

Again, thanks!

**Comment by jovpet** [comment]
Hello, I know you closed this issue, but I have similar problem. I've applied domino, and after that is seems to show some problem with require:

```
/.../dist/server.js:125910
    var matchesMethod = Element.prototype.matches ||
                        ^

ReferenceError: Element is not defined
    at /.../dist/server.js:125910:25
    at module.exports.Object.defineProperty.value (/.../dist/server.js:125811:13)
    at Object.module.exports.Object.defineProperty.value (/.../dist/server.js:125813:2)
    at __webpack_require__ (/.../dist/server.js:21:30)
    at Module.<anonymous> (/.../dist/server.js:189802:76)
    at __webpack_require__ (/.../dist/server.js:21:30)
    at Object.@fullcalendar/angular (/.../dist/server.js:182770:18)
    at __webpack_require__ (/.../dist/server.js:158251:30)
    at Object../src/app/publication/publication.module.ngfactory.js (/.../server.js:172385:11)
    at __webpack_require__ (/.../dist/server.js:158251:30)
```

here is my server.ts

```typescript
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import { enableProdMode } from '@angular/core';
import { ngExpressEngine } from '@nguniversal/express-engine';
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';

import * as express from 'express';
import * as bodyParser from 'body-parser';
import * as cors from 'cors';
import * as compression from 'compression';

const Blob = require('node-blob');

enableProdMode();

export const app = express();

app.use(compression());
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync(path.join('dist', 'browser', 'index.html')).toString();
const win = domino.createWindow(template);
global['window'] = win;
global['window']['URL'] = {};
global['self'] = {};
const createObjectURL = require('create-object-url');
global['window']['URL'].createObjectURL = createObjectURL;
global['document'] = win.document;
global['self']['navigator'] = {};
global['Blob'] = Blob;
global

// const DIST_FOLDER = join(process.cwd(), 'dist');

const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/server/main');

app.engine(
  'html',
  ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [provideModuleMap(LAZY_MODULE_MAP)]
  })
);

app.set('view engine', 'html');
app.set('views', './dist/browser');

app.get('/redirect/**', (req, res) => {
  const location = req.url.substring(10);
  res.redirect(301, location);
});

app.get(
  '*.*',
  express.static('./dist/browser', {
    maxAge: '1y'
  })
);

app.get('/*', (req, res) => {
  res.render('index', { req, res }, (err, html) => {
    if (html) {
      res.send(html);
    } else {
      console.error(err);
      res.send(err);
    }
  });
});
```

any ideas or tips on that? thanks!

**Comment by amunir9** [comment]
any fix for this?

**Comment by ajayashok** [comment]
any solution for that???
is it possible to solve the issue on angular universal?

**Comment by irustm** [comment]
@jovpet @ajayashok @amunir9 

If you still have a similar problem, try using this starter: https://github.com/Angular-RU/angular-universal-starter/

If you're still in trouble, write to me about it.

**Comment by sherry9872** [comment]
Facing the issue 
webpack:///./node_modules/@fullcalendar/core/main.esm.js?:253
[2] var matchesMethod = Element.prototype.matches ||
[2]                     ^
[2]
[2] ReferenceError: Element is not defined
[2]     at eval (webpack:///./node_modules/@fullcalendar/core/main.esm.js?:253:21)
[2]     at Module../node_modules/@fullcalendar/core/main.esm.js 

with the above repo

**Comment by zaid4kspr** [comment]
I fixed the problem using domino `// ssr DOM
const domino = require('domino');
const fs = require('fs');
const path = require('path');
var Element = domino.impl.Element; // etc

// index from browser build!
const template = fs.readFileSync(path.join(__dirname, '.', 'browser','index.html')).toString();
// for mock global window by domino
const win = domino.createWindow(template);
// from server build
// const files = fs.readdirSync(`${process.cwd()}/dist-server`);
// mock
global['window'] = win;
// not implemented property and functions
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
// mock documnet
global['document'] = win.document;
global['Element'] = Element;

// othres mock
global['CSS'] = null;
// global['XMLHttpRequest'] = require('xmlhttprequest').XMLHttpRequest;
global['Prism'] = null;


`

**Comment by gitalvininfo** [comment]
Where do you exactly put the code inside server.ts

This is currently my server.ts. Been dealing with this problem for almost  a week now. Please help.


`import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';


// The Express app is exported so that it can be used by serverless Functions.
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/gradus/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // app.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run() {

  const port = process.env.PORT || 4000;


  
  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
`

**Comment by jgu7man** [comment]
> run fullcalendar without server
> example:
> 
> ```ts
>     private isServer: boolean;
> 
>     constructor(
>         private tstate: TransferState,
>         @Inject(PLATFORM_ID) platformId
>     ) {
>         this.isServer = isPlatformServer(platformId);
>     }
> ```

Hi, how and where I do this?

**Comment by hamzou247** [comment]
Hello everybody,

I have been trying with all the proposed solutions but no luck. Does anyone get passed this error. I think i soved it somehow in the past but i have unfortunaltely lost the related code. Can anyone help me please? i'm using version 4.4.2

**Comment by pertakhia** [comment]
Hello everyone, I'm using full calendar in Angular Universal, however when I import FullCalendarModule in app.module.ts file, and run "npm run dev:ssr " it gives the following error  { ReferenceError: document is not defined
    at Module.42075 (C:\Users\New User\Desktop\schedule\dist\schedule\server\vendor.js:320130:26)
    at __webpack_require__ (../src/app/app.component.css:8:1)
    at Module.51174 (../src/app/app.component.css:8:1)
    at __webpack_require__ (../src/app/app.component.css:8:1)
    at Module.59229 (../src/app/app.component.css:8:1)
    at __webpack_require__ (../src/app/app.component.css:8:1)
    at Module.63370 (../src/app/app.component.css:8:1)
    at __webpack_require__ (../src/app/app.component.css:8:1)
    at Module.84362 (../src/app/app.component.css:8:1)
    at __webpack_require__ (../src/app/app.component.css:8:1)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:1479} . I have tried all the suggested methods and I have also used ChatGpt but I can't solve the problem. Can you just say that full calendar is supported in angular universal?  Thanks to all

**Comment by gitalvininfo** [comment]
Yes it's because you are rendering on a server and Document, LocalStorage, Window and other browser/client related keywords does not exist on the server.

What I did was this 

```
import { ..., PLATFORM_ID, ... } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';


constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
){
    if (isPlatformBrowser(this.platformId)) {
       // Your client side code
    }
}
```

Wrap all your client side code to platformBrowser.

**Comment by gitalvininfo** [comment]
Yes fullcalendar supports angular universal and I manage to get it work

**Comment by pertakhia** [comment]
@gitalvininfo  First of all, thanks for the feedback.

The problem is that as soon as I import the FullCalendarModule in the app.module.ts file.

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { FullCalendarModule } from '@fullcalendar/angular';

@NgModule({
   statements: [
     AppComponent
   ],
   imports: [
     BrowserModule.withServerTransition({ appId: 'serverApp' }),
     AppRoutingModule,
     FullCalendarModule // here
   ],
   providers: [],
   bootstrap: [AppComponent]
})
export class AppModule { }

And I run the command npm run build:ssr && npm run serve:ssr
Then it returns an error in the following form
 (ReferenceError: document is not defined
     at C:\Users\shpertakhia\Desktop\calendar-ssr\dist\calendar-ssr\server\main.js:1:3968907
     at C:\Users\shpertakhia\Desktop\calendar-ssr\dist\calendar-ssr\server\main.js:1:3979552
     at Object.<anonymous> (C:\Users\shpertakhia\Desktop\calendar-ssr\dist\calendar-ssr\server\main.js:1:3979784)
     at Module._compile (node:internal/modules/cjs/loader:1159:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
     at Module.load (node:internal/modules/cjs/loader:1037:32)
     at Module._load (node:internal/modules/cjs/loader:878:12)
     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
     at node:internal/main/run_main_module:23:47

Node.js v18.12.1)

I wonder where in the app.module.ts file I should implement your advice to use this

constructor(
     @Inject(PLATFORM_ID) private platformId: Object,
){
     if (isPlatformBrowser(this.platformId)) {
        // Your client side code
     }
}
I'm a bit confused. Thank you and I look forward to hearing from you.

**Comment by pertakhia** [comment]
> Yes fullcalendar supports angular universal and I manage to get it work

Can you give me any advice?

**Comment by gitalvininfo** [comment]
Hello @pertakhia did you manage to solve this issue? When you encounter this error ReferenceError: document is not defined does your app does not run?

**Comment by pertakhia** [comment]
> Hello @pertakhia did you manage to solve this issue? When you encounter this error ReferenceError: document is not defined does your app does not run?

Hi, yes I solved this problem by using lazy-loading. Thanks for the help.

**Comment by gitalvininfo** [comment]
In app.component.ts

```
isBrowser = false;

  constructor(
    @Inject(PLATFORM_ID) private platformId: object
  ) {
    if (isPlatformBrowser(this.platformId)) {
      this.isBrowser = true
    }
  }
```

In app.component.html
`<full-calendar *ngIf="isBrowser" [options]="calendarOptions"></full-calendar>
`


For future readers, you could try this one to prevent reference errors
