### ISSUE TITLE
font awesome icons on event title (angular version)

### ISSUE THREAD

**Issue by gjpennell** [fullcalendar/fullcalendar-angular#201]
Is it possible to display a font-awesome icon alongside the event title with the fullCalendar-angular?  If so, can you please provide a sample, or possible alternative solution?  I have tried the eventRender but to no avail.

**Comment by gjpennell** [comment]
Nevermind, I was able to figure it out.  Was going off of an older version, it seemed like.

**Comment by MiguelGonzalezAravena** [comment]
> Nevermind, I was able to figure it out. Was going off of an older version, it seemed like.

How did you get it?

**Comment by yuricamara** [comment]
How did you get it, @gjpennell ?

**Comment by pierresh** [comment]
Hello,

yes, it would be interesting to know how to add icons in event title ^^

**Comment by jolle-c** [comment]
I use classes for that. The event object has a param classNames. When, on the server, compiling the list of events to show I add classes to classNames for any icon I want to show.

On client I then have css definitions for the different classes:

.fc-event.hasattention::after,
.fc-event.hasdescr::after,
.fc-event.hasattention.hasdescr::after {
    content: "";
    position: absolute;
    top: 4px;
    right: 0;
    height: 13px;
    background-repeat: no-repeat;
}

.fc-event.hasattention::after {
    width: 13px;
    background: url(/assets/icons/jina-svg/exclamation-icon.svg) top right;
    background-size: 100%;
}
.fc-event.hasdescr::after {
    width: 13px;
    background: url(/assets/icons/jina-svg/star-icon.svg) top right;
    background-size: 100%;
}

.fc-event.hasattention.hasdescr::after {
    width: 27px;
    background-image: url(/assets/icons/jina-svg/star-icon.svg),
        url(/assets/icons/jina-svg/exclamation-icon.svg);
    background-size: 13px;
    background-position: 0 0, 13px 0;
}

Works fairly well.

/Jolle
