### ISSUE TITLE
allDaySlot to false rendering issue

### ISSUE THREAD

**Issue by fabdeceglia** [fullcalendar/fullcalendar-angular#207]
Hi everyone,

I am using the latest version of the Angular wrapper for Fullcalender.
I configured my calendar to show the **allDaySlot**. I set also the **allDayText** to a my specific string and a default value by using **allDayDefault** (to false).

The slot is correctly rendered when the allDay of the event in the current day is set to true:

[See here](https://ibb.co/nQjRPd9)

The slot is not correctly rendered when the allDay is false:

[See here](https://ibb.co/WVsfFFQ)

Is there something that am i missing in the configuration?

**Comment by irustm** [comment]
please replace your issue in stackblitz. 
demo: https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by irustm** [comment]
I'm closing this issue. If there are any questions, please create a new issue.
