### ISSUE TITLE
Can't get the event.element

### ISSUE THREAD

**Issue by lilworks** [fullcalendar/fullcalendar-angular#208]
I try to customize some event 
```
  eventRender(model) {
    if(model.event.id == 1515) {
      model.el.css({"backgroundColor": "black", "color": "white"});
    }
  }
```
But I got 

`model.el.css is not a function`

when I log model.el I get the good element.... I also tried model.element as I saw in some exemple. But this property doesn't seem to exist anymore

**Comment by irustm** [comment]
Yes, element css function it's JQuery function, before @fullcalendar 4,
 use nativeElement functions
