### ISSUE TITLE
is possible to update angular dependency to 8.0?

### ISSUE THREAD

**Issue by nevernet** [fullcalendar/fullcalendar-angular#209]

**Comment by irustm** [comment]
You about peerDependencies ?

**Comment by nevernet** [comment]
@irustm yes :)

**Comment by AlexAegis** [comment]
Please upgrade to Angular 8

**Comment by Olgagr** [comment]
@irustm Any update on that? It's blocking us to upgrade NG version in our project.

**Comment by mikolajgrzyb** [comment]
I would appreciate it too! :)

**Comment by jolle-c** [comment]
As a tip. I run FullCalendar-angular with Angular 8.1.2. What’s the problem?

HDB
Jolle

**Comment by irustm** [comment]
fixes in #269

**Comment by arshaw** [comment]
v4.4.0, just released, adds angular 8 support:
https://github.com/fullcalendar/fullcalendar-angular/releases/tag/v4.4.0
