### ISSUE TITLE
validRange issue with week and month layout

### ISSUE THREAD

**Issue by ips-illuminz** [fullcalendar/fullcalendar-angular#210]
Hi, Thanks for this great module.

I'm having one issue with layout of Month and week when using validRange. If i choose days range of 10 days then it seems working fine, but when i use 2-3 days range then it has some weird layout issues with Month and Week calendars. If i click on Month and then Week the layout get distorted. 

I have recreated the issue on stackblitz, please have a look and let me know how to solve this:
https://stackblitz.com/edit/fullcalendar-angular-example

**Comment by irustm** [comment]
try to write in the main branch 
https://github.com/fullcalendar/fullcalendar/issues

**Comment by ips-illuminz** [comment]
@irustm Thanks for the update, I'm having issue in validRange while using Angular module of fullcalendar, that's why i have highlighted the issue here. Okay no worry, i will write the same problem there as well.

**Comment by irustm** [comment]
ok, i'm close this issue, 

If any suggestions, then write to me about it.
