### ISSUE TITLE
jalali calendar support

### ISSUE THREAD

**Issue by mahsaml90** [fullcalendar/fullcalendar-angular#211]
Is there any way that i could change the moment.js to jalali-moment..js?

 dates and calculations in jalali calendars are different from other calendars

i think we need a provider that help us to define what calendar js file we need 

just like this library : https://stackblitz.com/edit/angular-262ncv?file=demo%2Fjalali-date-formatter.provider.ts

as you see we can overwrite providers.

**Comment by irustm** [comment]
Hi! You can use locale https://fullcalendar.io/docs/locale

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1813
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by allahyar** [comment]
Is there no hope of supporting the Jalali calendar?
Jalali calendar calculation is different and this is not implemented.
This library needs a capability for adapter class injection to set [Jalali Moment](https://www.npmjs.com/package/jalali-moment)

For example : https://gist.github.com/moein459/768318ccb67a0daaf8234d742753cb46
