### ISSUE TITLE
Does the library support mobile view also?

### ISSUE THREAD

**Issue by muhammadali1995** [fullcalendar/fullcalendar-angular#213]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3187
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by coda-apps** [comment]
I am a user of previous versions of FC, and need to use it for a new project. Is the new version fully responsive? i haven't seen this mentioned anywhere on the site, only a few references in tickets here, but even there its not really clear where the requests for responsive view stands. 
Would love to hear, thanks! 
Apologies for asking a non-bug question here.

**Comment by optiman917** [comment]
I think fully responsive is not supported well in FC, I love to work with FC but it is not easy to make it fully responsive.
I have checked this URL and used it.  [https://fullcalendar.io/docs/custom-view-with-js](https://fullcalendar.io/docs/custom-view-with-js)
