### ISSUE TITLE
External events (Angular version) - timeGridPlugin

### ISSUE THREAD

**Issue by mstopczyk** [fullcalendar/fullcalendar-angular#214]
I followed the demo with external events mentioned in https://github.com/fullcalendar/fullcalendar-angular/issues/192 and it works fine.
But I wanted to add other views to calendar - especially I wanted to use _timeGridPlugin_ (to have "Week" and "Day" view).
I added required import to _app-components.ts_
`import timeGridPlugin from '@fullcalendar/timegrid';`

I extended options like below:
```
    this.options = {
      (...)
      header: {
        left: 'prev,next today myCustomButton',
        center: 'title',
        right: 'dayGridMonth,**timeGridWeek,timeGridDay**'
      },
     (...)
      plugins: [dayGridPlugin, interactionPlugin, **timeGridPlugin**]
    };
```

The result is that I see additional buttons on Calendar - but dragging external events stopped working...

**Comment by irustm** [comment]
Hi! please reproduce your issue in stackblitz

**Comment by mstopczyk** [comment]
Hi,
This is stackblitz that reproduces the problem.
https://stackblitz.com/edit/fullcalendar-angular-demo-9kttek?file=src%2Fapp%2Fapp.component.ts

I tried couple of options but without luck...

**Comment by irustm** [comment]
I put the plugin in the demo, and it all worked out

https://stackblitz.com/edit/fullcalendar-angular-demo?file=src%2Fapp%2Fapp.component.ts

**Comment by mstopczyk** [comment]
Irustm, thank you for your help.
So are you able to change the view to dayview (click top right button) and drag an event to proper time slot on this view?

**Comment by irustm** [comment]
Yeah, there's a problem, I think it's because of the stackblitz's internal window.

**Comment by mstopczyk** [comment]
I think this is something else. I run the same code on my stand-alone application (locally, without stackblitz) and I have the same situation...

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I believe the issue is that `daygrid/main.css` is not getting included.  I wasn't able to get it working in your demo but get the same result if I remove that CSS from the drag and drop demo:

https://codepen.io/acerix/pen/JjGvJoy?editors=001

**Comment by SAI55874** [comment]
In Angular 16 fullcalender v6 how can I get external events? The above stuff is not working.
