### ISSUE TITLE
eventAfterAllRender not found

### ISSUE THREAD

**Issue by haseebahmad109** [fullcalendar/fullcalendar-angular#215]
Unable to find eventAfterAllRender after fullcalendar angular shift from ng-fullcalendar. This event is also mentioned in fullcalendar docs. Is there an alternative available for this?

**Comment by kacime** [comment]
Hello,
I have the same problem so if you have found a solution I am also interested.

**Comment by haseebahmad109** [comment]
> Hello,
> I have the same problem so if you have found a solution I am also interested.

Not a solution to eventAfterAllRender but my purpose for using was scroll to current day however an option for scrollTime is given for that purpose however I was unable to find any alternative to eventAfterAllRender function

**Comment by irustm** [comment]
https://fullcalendar.io/docs/upgrading-from-v3

**Comment by irustm** [comment]
I'm closing this issue. If there are any questions, please create a new issue.
