### ISSUE TITLE
agendaWeek defaultView not recognized

### ISSUE THREAD

**Issue by advisingai-user2** [fullcalendar/fullcalendar-angular#217]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

I tried loading the full-calendar component in Angular with defaultView='agendaWeek' and my browser prints an error saying that agendaWeek is not recognized.

`The FullCalendar view "agendaWeek" does not exist. Make sure your plugins are loaded correctly.`

Is there a specific plugin I need to grab for this to work?

**Comment by irustm** [comment]
Hey! Add plugin for this
https://fullcalendar.io/docs/timegrid-view
and see all plugins https://fullcalendar.io/docs/upgrading-from-v3
