### ISSUE TITLE
calendar.getResourceById is not a function

### ISSUE THREAD

**Issue by haroldheim** [fullcalendar/fullcalendar-angular#218]
Hello, I get the following error message **calendar.getResourceById is not a function**, when trying to click on a date using the _dateClick_ emitted event. 

I'm using the following plugins: _resourceTimelinePlugin_, _interactionPlugin_.

Am I doing something wrong?

Thanks for you reply.

**Comment by irustm** [comment]
Hi!
please reproduce your issue in stackblitz.com
https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by haroldheim** [comment]
Didn't need to.
Updated to the latest version of the component (4.2.1) fixed the problem.
Regards,
