### ISSUE TITLE
ERROR TypeError: Cannot read property 'getApi' of undefined

### ISSUE THREAD

**Issue by andrejm7** [fullcalendar/fullcalendar-angular#219]
what's the problem?

ERROR TypeError: Cannot read property 'getApi' of undefined

`        this.fullcalendar.getApi().refetchEvents();
`

**Comment by irustm** [comment]
Hi! please reproduce your issue in stackblitz

you may be trying to call the function before the fullcalendar appeared

**Comment by makkaronis4e** [comment]
When do you call this method? inside ngOnInit()?

**Comment by andrejm7** [comment]
In ngOnInit () I use this.options = [];

I created a render () method and I use above the constructor () {}

Would be like this:

```
render () {
this.fullcalendar.getApi (). render ();
}

constructor () {}
```

**Comment by makkaronis4e** [comment]
Im not sure that i fully understood your approach. But id reccomend you to call this method inside ngAfterViewInit. You can reach this api only after your component finishes rendering calendar

ngAfterViewInit(): void {
   this.calendarApi = this.calendarComponent.getApi();
}

**Comment by Anil-Toxy** [comment]
hii , well i am getiing the same issue tried in afterview cycle but it show the same warning :  Cannot read property 'refetchEvents' of undefined !!

- i am getting bunch of data from na change event of an input box through ajn api and then pushing it to a array of event (full calender) but it doestn't render it i tried calender api ( renderAllevent , progressiveEventRendering etc ) but Cannot read property '' of undefined.

**Comment by roestigraben** [comment]
Hi there,
I run into the same problem

**Comment by rjs123431** [comment]
try to enclose it inside settimeout
`getCalendarApi() {
        setTimeout(() => {
            this.calendarApi = this.monthFullCalendar.getApi();
        });
    }`

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by georgisoft2020** [comment]
maybe in the template of the component you forgot to put the full-calendar element.
<full-calendar #calendar [options]="calendarOptions" deepChangeDetection="true"></full-calendar>

**Comment by weilies** [comment]
> Sorry for the delay in responding to your issue, I have just begun triaging on this repo.
> 
> If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

i hit the same error and here is the demo https://codesandbox.io/s/ng-fullcal-ad9-9xy4q
Thanks for the support.
