### ISSUE TITLE
Output event navLinkDayClick missing

### ISSUE THREAD

**Issue by nspourriel** [fullcalendar/fullcalendar-angular#220]
Bug Reports

The navLinkDayClick output event is missing on the fullcalendar angular plugin.
https://fullcalendar.io/docs/navLinkDayClick

Clicking on a navLink always navigates to the clicked date but the alert is not displayed:
 https://stackblitz.com/edit/angular-7chhen

**Comment by irustm** [comment]
Thanks! fixes in next version
