### ISSUE TITLE
I had an issue while integrating Vertical Resource View with premium licence key.

### ISSUE THREAD

**Issue by rafee11** [fullcalendar/fullcalendar-angular#221]
I am a Premium user and I am facing some issues on npm package files while integrating Vertical Resource View (https://fullcalendar.io/docs/vertical-resource-view)

Package name : npm install --save @fullcalendar/core @fullcalendar/resource-timegrid,

I have installed this package successfully but there is an error while compile (ng serve). I have attached the screen shot of the errors. I am using Angular 7 with latest typescript.

![Capture 51](https://user-images.githubusercontent.com/23078836/62116805-6cd3a300-b2d8-11e9-86c6-125df3245d4c.PNG)

**Comment by irustm** [comment]
hi! try this demo: https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by rafee11** [comment]
@irustm Thanks for the link, but that link is not having **resourceTimeGrid** plugin. I need a demo for  (https://fullcalendar.io/docs/vertical-resource-view) **resourceTimeGrid** plugin in Angular v7.

**Comment by irustm** [comment]
ghm.., i'm add  `'resourceTimeGridDay`', to demo in stackblitz and not see problems in console,

please, tell me about your version, angular and typescript.

command: `ng version` in project folder, where there's `angular.json` file

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
