### ISSUE TITLE
How to utilize fullcalendar('getView') ?

### ISSUE THREAD

**Issue by shyamal890** [fullcalendar/fullcalendar-angular#223]
`@ViewChild('calendar') calendar;`

Then accessing `calendar.fullcalendar('getView')` not working. How as `calendar` component doesn't have fullcalendar.

**Comment by irustm** [comment]
Please try reproduce this issue on stackblitz
https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by irustm** [comment]
Did this answer help you?

**Comment by shyamal890** [comment]
@irustm Here's stackblitz file of what I am trying to achieve.

Please check `getStartAndEnd` function.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

`getView` is from version 3, in v4 you can get it with `calendar.view`.

https://fullcalendar.io/docs/v4/upgrading-from-v3#core-changes
