### ISSUE TITLE
Scheduler error TS2339

### ISSUE THREAD

**Issue by ricavir11** [fullcalendar/fullcalendar-angular#224]
I just update my existing angular application by updagrading to Angular 7 FullCalendar v4.

I was using FullCalendar v3 with ng-fullcalendar deprecated component.

After updgrade and some fullcalendar API changes and CSS adds, my project runs perfectly.

Now, I want to buy a licence of Scheduler but before wanted to test it.
I've added the plugin resource-timeline and followed documentation.

The problem is that I'm getting a lot of error TS2339 in angular CLI... it's like fullcalendar core is not recognized after adding scheduler.

![image](https://user-images.githubusercontent.com/25507232/62421255-3a8ec080-b69f-11e9-8c00-8a8a6894cfc7.png)

Do you have any idea how to fix this ?

I'm using these versions :
"@angular/core": "^7.0.0",
     "@fullcalendar/angular": "^4.2.1",
    "@fullcalendar/core": "^4.2.0",
    "@fullcalendar/daygrid": "^4.2.0",
    "@fullcalendar/interaction": "^4.2.0",
    "@fullcalendar/moment": "^4.2.0",
    "@fullcalendar/resource-timeline": "^4.2.0",
    "@fullcalendar/timegrid": "^4.2.0",
"typescript": "3.1.3",

**Comment by irustm** [comment]
Unfortunately, I don't work with sheduller. Maybe @arshaw will help

**Comment by ricavir11** [comment]
I got it to work.
I forgot to add required css links in angular.json file.
