### ISSUE TITLE
(dateClick) not working

### ISSUE THREAD

**Issue by stolotti** [fullcalendar/fullcalendar-angular#225]
I've tried to add (dateClick) input directive but it seems not working
I've tried to add (eventClick) the same way and it works correctly. 

   "@fullcalendar/angular": "^4.2.1",
    "@fullcalendar/core": "^4.2.0",
    "@fullcalendar/daygrid": "^4.2.0",
    "@fullcalendar/list": "^4.2.0",

**Comment by irustm** [comment]
Hi! see this demo please app.component.html#13

https://stackblitz.com/edit/fullcalendar-angular-demo?file=src%2Fapp%2Fapp.component.html

**Comment by irustm** [comment]
@stolotti 
Did this answer help you?

**Comment by JoabChua** [comment]
U need this for dateClick to work. It was not that clear in the documentation.

`import interactionPlugin from '@fullcalendar/interaction'; // for dateClick`

Hope this helps. :)
