### ISSUE TITLE
Is support Angular 5 version?

### ISSUE THREAD

**Issue by RamuDhanush** [fullcalendar/fullcalendar-angular#227]
**In my package.json :**   

"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@auth0/angular-jwt": "^2.1.1",  
    "@fullcalendar/angular": "^4.1.0",
    "@fullcalendar/core": "^4.1.0",
    "@fullcalendar/daygrid": "^4.1.0",
    "@fullcalendar/interaction": "^4.1.0",
    "@fullcalendar/timegrid": "^4.1.0",
    "@fullcalendar/list": "^4.1.0",
...
}

**In app.module.ts :**

import { FullCalendarModule } from '@fullcalendar/angular';

imports: [
    BrowserModule,
    FullCalendarModule,
    ...
  ],

**In Html :**

<full-calendar #calendar
               defaultView="dayGridMonth"
               [header]="{
                            left: 'prev,next today',
                            center: 'title',
                            right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
                           }"
               [plugins]="calendarPlugins"
               [weekends]="calendarWeekends"
               [events]="calendarEvents"
               (dateClick)="handleDateClick($event)"></full-calendar>

**In TS :**

import { Component, ViewChild, OnInit } from '@angular/core';
import { FullCalendarComponent } from '@fullcalendar/angular';
import { EventInput } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGrigPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';

export class HomeComponent {
 @ViewChild('calendar') calendarComponent: FullCalendarComponent; // the #calendar in the template

    calendarVisible = true;
    calendarPlugins = [dayGridPlugin, timeGrigPlugin, interactionPlugin];
    calendarWeekends = true;
    calendarEvents: EventInput[] = [
        { title: 'Event Now', start: new Date() }
    ];

    toggleVisible() {
        this.calendarVisible = !this.calendarVisible;
    }

    toggleWeekends() {
        this.calendarWeekends = !this.calendarWeekends;
    }

    gotoPast() {
        let calendarApi = this.calendarComponent.getApi();
        calendarApi.gotoDate('2000-01-01'); // call a method on the Calendar object
    }

    handleDateClick(arg) {
        if (confirm('Would you like to add an event to ' + arg.dateStr + ' ?')) {
            this.calendarEvents = this.calendarEvents.concat({ // add new event data. must create new array
                title: 'New Event',
                start: arg.date,
                allDay: arg.allDay
            })
        }
    }  

}

Once execute npm start, I got an error. Refer screen shot at below

![Err_Angular5_FullCalendar](https://user-images.githubusercontent.com/38865679/63251370-6fb01c80-c222-11e9-905b-cb74335ee5c9.png)

Thanks,
Ramu

**Comment by irustm** [comment]
try use old ng-fullcalendar please https://www.npmjs.com/package/ng-fullcalendar

or update your app to angular 7^

**Comment by RamuDhanush** [comment]
Actually I upgrade the typescript version:      "typescript": "~3.1.1",
then it works fine.

**Comment by irustm** [comment]
cool! i'm close this issue

if any questions ping me,

**Comment by amanpreet-dev** [comment]
> Actually I upgrade the typescript version: "typescript": "~3.1.1",
> then it works fine.

Did you change anything else too? I am getting below error if I upgrade.
`Could not find local "typescript" package.The "@ngtools/webpack" package requires a local "typescript@^2.0.2" package to be installed.`
