### ISSUE TITLE
navLinks throws Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by Pingolus** [fullcalendar/fullcalendar-angular#229]
### Bug Reports
There's an issue with navLinks : it seems not to work in combination with other properties (I don't know still which one). 

To reproduce it, you just have to add [navLinks]="true" to component from official runnable angular project which is cloned here : https://stackblitz.com/edit/github-j8rtc7

You'll see that navigation is not working and there's an error on console if you click on a date in day right corner.

Thanks for your support

**Comment by arshaw** [comment]
fixed in https://github.com/fullcalendar/fullcalendar-angular/releases/tag/v4.4.0
