### ISSUE TITLE
How to restrict user not to select background event.

### ISSUE THREAD

**Issue by ikismail** [fullcalendar/fullcalendar-angular#230]
I'm trying to restrict the user not to select the background events. 
for example 

```
<full-calendar
...
[eventsSources]="eventSource"
[selectable]="true"
(select)="createEvent($event)"
></full-calendar>
```

![image](https://user-images.githubusercontent.com/17190913/63760874-c500c380-c8dd-11e9-9a63-2cb699490880.png)

I went through the documentation [selectOverlap](https://fullcalendar.io/docs/selectOverlap)
I tried to integrate it my component. but there is no export function for selectOverlap

Can anyone help me with that..

**Comment by irustm** [comment]
Hi

use selectOverlap as object function
```ts
 options {
      selectOverlap: function(event) {
        return true;
      },
```

```html
<full-calendar
...
[eventsSources]="eventSource"
[selectable]="true"
[selectOverlap]="options.selectOverlap"
(select)="createEvent($event)"
></full-calendar>
```

**Comment by ikismail** [comment]
thanks @irustm will try..

**Comment by acerix** [comment]
If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
