### ISSUE TITLE
Is events rendering in IE 11 browser with using Angular 5 version?

### ISSUE THREAD

**Issue by RamuDhanush** [fullcalendar/fullcalendar-angular#231]
Hi,

Events are not rendering in IE 11 browser but it works fine in Chrome, Edge and Firefox.

Refer screen shots,

**IE:**
![image](https://user-images.githubusercontent.com/38865679/64232352-aa62b780-cea6-11e9-81ef-74012818ba83.png)

**Chrome:**
![image](https://user-images.githubusercontent.com/38865679/64232397-bc445a80-cea6-11e9-9e84-3f9e8e4aca0f.png)

**In HTML:**

 <full-calendar #calendar
                                       height="auto"
                                       fixedWeekCount="false"
                                       editable="false"
                                       defaultView="listMonth"
                                       displayEventTime="true"
                                       timezone="local"
                                       eventLimit="false"
                                       [eventTimeFormat]="{
                                                            hour: 'numeric',
                                                            minute: '2-digit',
                                                            omitZeroMinute: true,
                                                            meridiem: 'short'
                                                        }"
                                       [header]="{
                                                    left: '',
                                                    center: 'title',
                                                    right: 'prev,next today,dayGridMonth,listMonth'
                                                }"
                                       [buttonText]="{
                                                        dayGridMonth: 'Calendar',
                                                        listMonth: 'List' ,
                                                        today: 'Today'
                                                    }"
                                       [plugins]="calendarPlugins"
                                       [weekends]="calendarWeekends"
                                       [events]="calendarEvents"
                                       (eventRender)="handleEventRender($event)"
                                       (dateClick)="handleDateClick($event)"></full-calendar>

**In TS:**

import { FullCalendarComponent } from '@fullcalendar/angular';
import { EventInput } from '@fullcalendar/core';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGrigPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction'; // for dateClick
import listPlugin from '@fullcalendar/list';

  calendarEvents: EventInput[] = [
        {
            ID: '',
            title: 'WW',           
            start: new Date('2019-06-04 18:15:00'),
            end: new Date('2019-06-04 19:00:00'),            
            color: '#009390'
        },
        {
            ID: '',
            title: 'Financial Fitness',           
            start: new Date('2019-06-06 18:00:00'),
            end: new Date('2019-06-06 19:00:00'),           
            color: '#d95b1e'            
        },
        ....
        ....
       ];

**In Package.Json:**

   "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",  
    "@fullcalendar/angular": "^4.3.1",
    "@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@fullcalendar/timegrid": "^4.3.0",
    "@fullcalendar/list": "^4.3.0",

Thanks,
Ramu

**Comment by irustm** [comment]
uncomment polifills for IE in you angular app

**Comment by acerix** [comment]
If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
