### ISSUE TITLE
navLinks - TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by QuytNguyen** [fullcalendar/fullcalendar-angular#232]
Using configuration: (fullcalendar 4.3.1)
`<full-calendar #calendar
								   defaultView="dayGridMonth"
								   [selectMirror]="true" 
								   [eventLimit]="true" 
								   [allDaySlot]="false"
								   [selectable]="true"
								   [locale]="calendarLocale"
								   [eventTimeFormat]="eventTimeFormat"
								   [header]="{
												left: 'prev,next today',
												center: 'title',
												right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
											}"
								   [buttonText]="buttonText"
								   [plugins]="calendarPlugins"
								   [weekends]="calendarWeekends"
								   [navLinks]="true" 
								   (datesRender)="datesRender($event)"
								   (eventRender)="eventRender($event)"
								   (select)="handleDateClick($event)"
								   (eventClick)="eventClick($event)"></full-calendar>`
when I click day-number, it return error :

> core.js:1673 ERROR TypeError: Cannot read property 'emit' of undefined
>     at fullcalendar-angular.js:313
>     at HTMLAnchorElement.<anonymous> (main.esm.js:6622)
>     at HTMLElement.realHandler (main.esm.js:379)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:3815)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
>     at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
>     at invokeTask (zone.js:1540)
>     at HTMLElement.globalZoneAwareCallback (zone.js:1566)

Calendar works fine util I add  **[navLinks]="true"** 
Am I missing something?
Thanks!

**Comment by superjulius** [comment]
Any timeline of when **next-release** will be available ? We are migrating from FC 3.x and having navLinks working is required to preserve existing behaviors.
