### ISSUE TITLE
Visible range or Change View is not working in Angular Full Calendar

### ISSUE THREAD

**Issue by NaveenTula90** [fullcalendar/fullcalendar-angular#234]
I want to display the Month View based on Date Range provided. To implement this, i'm trying to use the visible range, which seems not working in angular full calendar.

Here is the demo url:  https://stackblitz.com/edit/fullcalendar-angular-example-sr2ecs

Is it possible to change the view and allowing it to display the Custom Date range ?
https://stackblitz.com/edit/github-w8tqcx

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

The issue is that `dayGridMonth` sets the range to one month, you can just use `dayGrid` instead: 

https://stackblitz.com/edit/fullcalendar-angular-example-tah9il?file=src%2Fapp%2Fapp.component.html
