### ISSUE TITLE
VS 2017 (file new) / Angular

### ISSUE THREAD

**Issue by mhectorgato** [fullcalendar/fullcalendar-angular#235]
VS 2017, file new ASP.NET Core Angular site (Angular: 6.1.10).

Followed the steps here: https://fullcalendar.io/docs/angular

******** ******** ******** ******** 
When F5-ing I get this:
Microsoft.AspNetCore.SpaServices:Information: Date: 2019-09-11T17:05:04.406Z
Hash: 05cdf82b9e9339bfa789
Time: 12171ms
chunk {main} main.js, main.js.map (main) 2.03 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 733 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.css, styles.css.map (styles) 130 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

Microsoft.AspNetCore.SpaServices:Information: ERROR in node_modules/@fullcalendar/core/main.d.ts(1197,54): error TS1144: '{' or ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1198,34): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1198,45): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1199,17): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1200,34): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1200,51): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1200,64): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1201,28): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1201,54): error TS1109: Expression expected.
node_modules/@fullcalendar/core/main.d.ts(1201,89): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1202,24): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1202,33): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1203,20): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1204,26): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1204,32): error TS1109: Expression expected.
node_modules/@fullcalendar/core/main.d.ts(1205,25): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1205,31): error TS1109: Expression expected.
node_modules/@fullcalendar/core/main.d.ts(1206,26): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1207,30): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1207,48): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1208,35): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1208,54): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1209,32): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1209,38): error TS1109: Expression expected.
node_modules/@fullcalendar/core/main.d.ts(1210,24): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1210,30): error TS1109: Expression expected.
node_modules/@fullcalendar/core/main.d.ts(1211,31): error TS1005: ',' expected.
node_modules/@fullcalendar/core/main.d.ts(1211,47): error TS1005: ';' expected.
node_modules/@fullcalendar/core/main.d.ts(1211,53): error TS1109: Expression expected.
node_modules/@fullcalendar/core/main.d.ts(1215,1): error TS1128: Declaration or statement expected.
node_modules/@fullcalendar/core/main.d.ts(2692,27): error TS1005: ',' expected.
node_modules/@fullcalendar/daygrid/main.d.ts(11,27): error TS1005: ',' expected.

******* ******* Version info ******* *******
Angular CLI: 6.0.8
Node: 10.6.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/language-service         6.0.5
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by superjulius** [comment]
https://fullcalendar.io/docs/angular mentions that the angular component supports Angular 7.

Try updating Angular to 7.x and TypeScript to 3.2.4 and check if it solves your issue.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

The v4 component needs Angular 7.  If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
