### ISSUE TITLE
Angular Themes

### ISSUE THREAD

**Issue by Ancient-Dragon** [fullcalendar/fullcalendar-angular#236]
On the demo's page: https://fullcalendar.io/#demo under theming you can find different themes. I was wondering how you select these themes when using the angular component, more specifically I'm looking to use materia, I've seen the documentation around the bootstrap one, but nothing around the others.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

The only built-in themes are `standard` and `bootstrap`, but 3rd party bootstrap themes should work:

https://fullcalendar.io/docs/bootstrap-theme#3rd-party-bootstrap-themes
