### ISSUE TITLE
eventMouseEnter & eventMouseLeave problem

### ISSUE THREAD

**Issue by mits87** [fullcalendar/fullcalendar-angular#242]
Hi, 

I'm trying use `eventMouseEnter` and `eventMouseLeave` and it doesn't work.
My template:

```
<full-calendar defaultView="dayGridMonth"
        (eventRender)="eventRender($event)"
        (eventMouseEnter)="eventMouseEnter($event)"
        (eventMouseEnter)="eventMouseLeave($event)"
        [plugins]="calendarPlugins"
        [events]="events">
</full-calendar>
```

my component.ts:
```
  eventMouseLeave(event) {
    console.log(event)
  }

  eventMouseEnter(event) {
    console.log(event)
  }
```

and any of my functions wasn't dispatched. 
Any Idea how to solve that?

**Comment by jolle-c** [comment]
> 29 sep. 2019 kl. 20:44 skrev Piotr Krajewski <notifications@github.com>:
> 
>         (eventMouseEnter)="eventMouseEnter($event)"
>         (eventMouseEnter)="eventMouseLeave($event)"
> 

Do you see the problem here?

I suggest
        (eventMouseEnter)="eventMouseEnter($event)"
        (eventMouseLeave)="eventMouseLeave($event)"

HDB
Jolle

**Comment by mits87** [comment]
> Do you see the problem here? I suggest (eventMouseEnter)="eventMouseEnter($event)" (eventMouseLeave)="eventMouseLeave($event)"

sorry this is my typo. Of course I have that:
```
  (eventMouseEnter)="eventMouseEnter($event)"
  (eventMouseLeave)="eventMouseLeave($event)"
```

and any event is not dispatching.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
