### ISSUE TITLE
Event setProp method params type

### ISSUE THREAD

**Issue by makkaronis4e** [fullcalendar/fullcalendar-angular#244]
Hi, 
im trying dynamically change classNames property for Event, but setProp **_val_** parameter 
defined as string, 
![image](https://user-images.githubusercontent.com/33792090/66122054-6965dc00-e5e7-11e9-9504-d1a19aec761b.png)

so it shows me an error when i put array as val:
![image](https://user-images.githubusercontent.com/33792090/66122073-7a165200-e5e7-11e9-8065-df4721ef20b9.png)

Nevertheless it still works even with array, but i think this parameter type should be changed to any.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
