### ISSUE TITLE
nowIndicator causes Angular testability to report as unstable

### ISSUE THREAD

**Issue by dillonm197** [fullcalendar/fullcalendar-angular#245]
Enabling nowIndicator for full-calendar causes Angular testabilities to report as unstable, causing e2e tests to act sporadically. 

You can check the testability status by using the following command in chrome tools:
`window.getAllAngularTestabilities()[0].isStable()`

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
