### ISSUE TITLE
ngFor on the screen is fired several times when mousemove on fullcalendar

### ISSUE THREAD

**Issue by Bemangular** [fullcalendar/fullcalendar-angular#246]
On a component, If I have fullcalendar with for example : 
```
<select>
<option *ngFor="let item of getTest()">{{item}}</option>
</select>
```
Where getTest() will return an array. 
Then the function getTest() will be fired every times the mouse move on the calendar.
Wich can slow down the use of full-calendar

**Comment by jolle-c** [comment]
Wrong approach. run your function once, for example inside ngOnInit. Let it populate a placeholder and use the placeholder in the option param.


HDB
Jolle

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
