### ISSUE TITLE
support for angular version 8

### ISSUE THREAD

**Issue by allyraza** [fullcalendar/fullcalendar-angular#250]
Hi there,

this library is not currently compatible with angular8 any plans to update it?

Thank you

**Comment by mitschmidt** [comment]
We are using it in a project with angular 8 and it works just fine. Probably this is just a matter of bumping the peer dependency version in `package.json`.

**Comment by Sobin99** [comment]
@mitschmidt  Are you able to use getapi() events in v8 as mentioned as mentioned in this #259

**Comment by irustm** [comment]
fixes in #269
