### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by NahuBocco** [fullcalendar/fullcalendar-angular#251]
Hi, is just a detail, but if i set locale property to "es", all change propertly except today button, it say "today" instead "hoy"

![image](https://user-images.githubusercontent.com/11876704/68672202-df872800-052f-11ea-9640-5d0b57665e81.png)

![image](https://user-images.githubusercontent.com/11876704/68672239-f0379e00-052f-11ea-88e1-1e55c315c463.png)

**Comment by Wiliamz** [comment]
I'm having the same issue

**Comment by jolle-c** [comment]
> 12 nov. 2019 kl. 13:37 skrev NahuBocco <notifications@github.com>:
> 
> Hi, is just a detail, but if i set locale property to "es", all change propertly except today button, it say "today" instead ”hoy"

Pending a correct solution I’ve had to set the button values when initiating the calendar.


<full-calendar #fullcalendar
  [defaultDate]="calendarOptions.defaultDate"
  [defaultView]="calendarOptions.defaultView"
  locale="sv"
  [allDayText]="calendarOptions.allDayText"
  [buttonText]="calendarOptions.buttonText"
  [customButtons]="calendarOptions.customButtons"
  [eventLimit]="calendarOptions.EventLimit"
  [eventLimitText]="calendarOptions.eventLimitText"
  [events]="calendarEvents"
  [firstDay]="calendarOptions.firstDay"
  [header]="calendarOptions.header"
  [noEventsMessage]="calendarOptions.noEventsMessage"
  [nowIndicator]="calendarOptions.nowIndicator"
  [plugins]="calendarOptions.plugins"
  [selectable]="calendarOptions.selectable"
  [weekends]="calendarOptions.weekends"
  [weekLabel]="calendarOptions.weekLabel"
  [weekNumberCalculation]="calendarOptions.weekNumberCalculation"
  [weekNumbers]="calendarOptions.weekNumbers"
  [height]="calendarOptions.height"
  [scrollTime]="'08:00:00'"
  (select)="handleDateSelect($event)"
  (eventClick)="handleEventClicked($event)"
  (eventMouseEnter)="handleEventMouseEnter($event)"
  (eventRender)="handleEventRender($event)"
  (dayRender)="handleDayRender($event)"
  (datesRender)="handleDatesRender($event)">
</full-calendar>


calendarOptions contains:

    buttonText: {
      today: 'Idag',
      month: 'Månad',
      week: 'Vecka',
      day: 'Dag',
      list: 'Lista'
    },


Hope this helps
Jolle

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

It sounds like the issue is that the locale file needs to be included, see: https://fullcalendar.io/docs/locale

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
