### ISSUE TITLE
Full Calendar Event is not displayed at the beginning

### ISSUE THREAD

**Issue by bfwg** [fullcalendar/fullcalendar-angular#257]
### Bug Reports
angular version: 8.1.2
fullcalendar version: 4.3.1
## Steps to recreate

```
    <full-calendar
      fxFlex
      #fullcalendar
      class="campus-dashboard__calendar"
      defaultView="timeGridWeek"
      contentHeight="auto"
      [plugins]="calendarPlugins"
      [header]="{
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth, timeGridWeek, timeGridDay'
      }"
      [events]="[{
        title: 'The Title',
        start: '2019-11-25T07:00:00',
        end: '2019-11-25T09:00:00'
      }]"
    ></full-calendar>
```

## Expected Result
The calendar loads with the event

## Actual Result
The event isn't there unless I click on a button or resize the window.

## Techincal Notes
The event will load if I use the below hack.
```
    @ViewChild('fullcalendar', { static: false }) fullcalendar: FullCalendarComponent;
    ...
    setTimeout(() => {
      this.fullcalendar.getApi().render();
    });
```

### Is your bug/feature applicable to the core project, without Angular?
no

**Comment by bfwg** [comment]
Relates to https://github.com/fullcalendar/fullcalendar/issues/4976

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
