### ISSUE TITLE
getAPI() method not working on Angular 8

### ISSUE THREAD

**Issue by roestigraben** [fullcalendar/fullcalendar-angular#259]
my setup is:

"dependencies": {
    "@angular/animations": "^8.2.13",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.4",
    "@angular/compiler": "~8.2.4",
    "@angular/core": "~8.2.4",
    "@angular/forms": "~8.2.4",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.4",
    "@angular/platform-browser-dynamic": "~8.2.4",
    "@angular/router": "~8.2.4",
    "@fullcalendar/angular": "^4.3.1",
    "@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@fullcalendar/resource-timeline": "^4.3.0",
    "@fullcalendar/timegrid": "^4.3.0",
    "@ng-bootstrap/ng-bootstrap": "^5.1.1",
    "ag-grid-angular": "^22.0.0",
    "ag-grid-community": "^22.0.0",
    "ag-grid-enterprise": "^22.0.0",
    "angular-font-awesome": "^3.1.2",
    "angular-in-memory-web-api": "^0.9.0",
    "bootstrap": "^4.3.1",
    "express": "^4.17.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "path": "^0.12.7",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "typescript": "~3.5.3",
    "zone.js": "~0.9.1"
  },

then I use pretty much the demo code and I run into a problem with the getAPI() method. Error is: 
 -->>> . Property 'getApi' does not exist on type 'FullCalendarComponent'.ts(2339)

gotoPast() {
    const calendarApi = this.fullcalendar.getApi().render();
    calendarApi.gotoDate('2000-01-01'); // call a method on the Calendar object
 }

When I use the exact same code with Angular 7 (exact config as per github clone and install), this passes nicely.

What happens?

Thanks

**Comment by vignesh-shiftX** [comment]
Any updates , still facing the getApi() not defined issues

**Comment by roestigraben** [comment]
sorry, I implemented my Calendar from scratch. hence did not do any more search.

**Comment by vignesh-shiftX** [comment]
Actually its working
when I changed my this part of code.
 Before Fix
`@ViewChild('#calendar', { static: true }) calendar: FullCalendarComponent;`

After Fix 
`@ViewChild('calendar', { static: true }) calendar: FullCalendarComponent;`

Removal of hashtag.A silly hashtag does it. I am using Angular 8 and getApi() works fine for me. This issue could be closed I guess.

**Comment by irustm** [comment]
@vignesh-shiftX thanks to reply, i close this issue,

@roestigraben If you have any more questions, please write to me

**Comment by constantinoschristoforou** [comment]
Accessing the getApi() method on ngAfterViewInit works
