### ISSUE TITLE
How to change local property of fullcalendar in Angular

### ISSUE THREAD

**Issue by ARoshanZamir** [fullcalendar/fullcalendar-angular#262]
I want to change `local `propety of **fullcalendar**, When I try to set it to `"en-gb"` but It does not work. Where I'm wrong ?

```
<full-calendar #calendar defaultView="dayGridMonth" [header]="{
  left: 'prev,next today',
  center: 'title',
  right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
}" local="en-gb" [plugins]="calendarPlugins" [weekends]="calendarWeekends" [events]="calendarEvents"></full-calendar>
```

typescript :

```
export class AppComponent {
  @ViewChild("calendar", { static: false })
  calendarComponent: FullCalendarComponent; // the #calendar in the template
  calendarPlugins = [dayGridPlugin, timeGrigPlugin, interactionPlugin];
  calendarWeekends = true;
  calendarEvents: EventInput[] = [{ title: "Event Now", start: new Date() }];
}
```

Based on "en-gb" the first day of week is Monday.

https://stackblitz.com/edit/angular-uf2v4r

**Comment by jolle-c** [comment]
Try using locale instead of local. If that doesn’t work set the option specifically.
Set FirstDay to 1

HDB
Jolle

Sent from a mobile device. Any anomalies is due to Autocorrect.

**Comment by ARoshanZamir** [comment]
Another way is to import `enGbLocale `

`import enGbLocale from '@fullcalendar/core/locales/en-gb';`

Then in your ngOnInit()

```
  ngOnInit() {
    setTimeout(() => { this.calendarComponent["calendar"].setOption('locale', enGbLocale); })
  }
```
It works perfectly

**Comment by EngelaereAntoine** [comment]
@ARoshanZamir 
Thanks for the type.
By the way, you can use `getApi()` instead of `["calendar"]`

```
  @ViewChild(FullCalendarComponent, {static: false})
  calendarComponent: FullCalendarComponent;
```
```
ngAfterViewInit(): void {
    this.calendarComponent.getApi().setOption('locale', frLocale);
}
```

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
