### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by likid** [fullcalendar/fullcalendar-angular#264]
I'm writing an app that uses jwt for request authentication and I am unable to know how to send the token in the headers in the way that fullcalendar request the events. As I can see, fullcalendar doesn't make use of Angular httpclient, so I can't use interceptor to inject the token in the header.
How is possible to do it or is it possible to create this feature?

**Comment by jolle-c** [comment]
> 10 dec. 2019 kl. 20:20 skrev Anderson Maciel <notifications@github.com>:
> 
> I'm writing an app that uses jwt for request authentication and I am unable to know how to send the token in the headers in the way that fullcalendar request the events. As I can see, fullcalendar doesn't make use of Angular httpclient, so I can't use interceptor to inject the token in the header.
> How is possible to do it or is it possible to create this feature?
> 

Greetings!

I am using Fullcalendar with Angular and JWT. It works with no hiccups. This is my setup:


The HTML:

<full-calendar #fullcalendar [defaultDate]="calendarOptions.defaultDate"
  [defaultView]="calendarOptions.defaultView" locale="en" [allDayText]="calendarOptions.allDayText"
  [buttonText]="calendarOptions.buttonText" [customButtons]="calendarOptions.customButtons"
  [eventLimit]="calendarOptions.EventLimit" [eventLimitText]="calendarOptions.eventLimitText"
  [events]="calendarEvents" [firstDay]="calendarOptions.firstDay" [header]="calendarOptions.header"
  [noEventsMessage]="calendarOptions.noEventsMessage" [nowIndicator]="calendarOptions.nowIndicator"
  [plugins]="calendarOptions.plugins" [selectable]="calendarOptions.selectable"
  [weekends]="calendarOptions.weekends" [weekLabel]="calendarOptions.weekLabel"
  [weekNumberCalculation]="calendarOptions.weekNumberCalculation" [weekNumbers]="calendarOptions.weekNumbers"
  [height]="calendarOptions.height" [scrollTime]="'08:00:00'" (select)="handleDateSelect($event)"
  (eventClick)="handleEventClicked($event)" (eventMouseEnter)="handleEventMouseEnter($event)"
  (eventRender)="handleEventRender($event)" (dayRender)="handleDayRender($event)"
  (datesRender)="handleDatesRender($event)">
</full-calendar>

Interesting part being [events]=”calendarEvents"

In the component javascript:

// initialise
calendarEvents: any[];

ngOnInit(): void {

  this.eventService.onEventsChanged
    .pipe(takeUntil(this._unsubscribeAll))
    .subscribe(events => {
	this.calendarEvents = events;
    });

... other stuff ...

}


In eventService:

import { FullCalendarComponent } from '@fullcalendar/angular';
import { EventInput } from '@fullcalendar/core’;

...

  onEventsChanged: BehaviorSubject<EventInput[]>;

...

  constructor(
...
) {
...
    this.onEventsChanged = new BehaviorSubject([]);
...
}



  getEvents(startdate: Date, enddate: Date): Promise<any> {

    this.activeStart = startdate;
    this.activeEnd = new Date(enddate);
    let params = {
      enddate: this.activeEnd.toISOString(),
      filterparams: this.onActiveFilterParams.getValue(),
      startdate: this.activeStart.toISOString(),
    }
    if (this.searchText.length) {
      params['searchtext'] = this.searchText;
    }
    return new Promise((resolve, reject) => {
      this.apiService.post('/get-events', params)
        .subscribe((response: any) => {
          if (response.success) {
            const records = response.result;
            this.setActiveTypes(records);
            this.onEventsChanged.next(records);
            resolve(records);
          }
        }, reject);
    });

  }



In apiService:

  post(path: string, body: Object = {}): Observable<any> {
    return this.http.post(
      `${environment.api_url}${path}`,
      JSON.stringify(body),
      { headers: this.setHeaders() }
    )
    .pipe(catchError((err: any) => {
      console.log('Error POST: ', catchError);
      return this.formatErrors(err);
    }));
  }


  public setHeaders(fileupload:boolean = false): HttpHeaders {
    const token = this.jwtService.getToken();
    let headersConfig;
    if (fileupload) {
      headersConfig = {
        'Accept': 'application/json'
      };

    } else {
      headersConfig = {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      };
    }

    if (token) {
      headersConfig['Authorization'] = `Token ${token}`;
    }

    return new HttpHeaders(headersConfig);
  }


Hope you can get the gist from the above snippets.


HDB
Jolle

**Comment by likid** [comment]
Hi @jolle-c , I've coded following the path you made to me. I created an eventService just the way you showed, but I now my calendar doesn't make any request to the backend to get the events. Do I have to make anything more to tell my calendar to use the eventService to fetch the events?

**Comment by jolle-c** [comment]
Sorry, I missed that part.

For me that is done using the datesRender call.

HTML:
(datesRender)="handleDatesRender($event)”

Component:
  handleDatesRender(e) {
    this.eventService.handleDatesRender(e);
  }


Service:
  handleDatesRender(e) {
    this.calendarOptions.defaultDate = e.view.currentStart;
    this.calendarOptions.defaultView = e.view.type;
    this.onOptionsChanged.next(this.calendarOptions);
    sessionStorage.setItem('JINA.Calendar.defaultDate', e.view.currentStart.toString());
    sessionStorage.setItem('JINA.Calendar.DefaultView', e.view.type);
    this.getEvents(e.view.activeStart, e.view.activeEnd);
  }

There are probably things in the last function you can (have to) remove but that’s directly from my solution.

HDB
Jolle

**Comment by likid** [comment]
Thank you so much @jolle-c , I could make it work and now I have all my events being show.
