### ISSUE TITLE
Drag & drop feature does not work correctly for multiple calendars

### ISSUE THREAD

**Issue by luninroman** [fullcalendar/fullcalendar-angular#266]
Consider the following information:

- I have a calendar on my main page.
- I have another calendar in a modal window.
- Both of the calendars have **editable** enabled and **droppable** disabled

Now, the modal calendar _drag & drop_ feature does not work (I can drag it but can't drop, it returns back to original position) if I try to drop an event somewhere in the main calendar area, even though the modal has higher z-index. At the same time, resize feature works fine for every calendar.

https://github-nn5fgt.stackblitz.io/

Steps to reproduce:
1) open stackblitz example
2) click on any day in any view
3) try to drag & drop the event in the modal

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
