### ISSUE TITLE
EndTime and StartTIme parsing.

### ISSUE THREAD

**Issue by rufataliy** [fullcalendar/fullcalendar-angular#267]
I am trying to have an event that has startDate and endDate also startTime and endTime. 
So I use antd timepicker and datepicker to set the values for date and time. But when parsing I get only start and end in event object. So I kinda need to have a property that will contain both time and date as a string.

Any idea how it is done?

You can fine code in my github account

https://github.com/rufataliy/Prodigy/tree/rerenderProblem

**Comment by irustm** [comment]
Try to format it to the desired fullcalednar date format, and convert it back to the same format if necessary.
