### ISSUE TITLE
Angular 8 npm warnings

### ISSUE THREAD

**Issue by szwowo** [fullcalendar/fullcalendar-angular#271]
Hi,
I have updated my angular project to angular 8 and after running `npm install` I have got this warnings:

`npm WARN @fullcalendar/angular@4.3.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN @fullcalendar/angular@4.3.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.`

Is there a way to fix this or do I need to wait for fullcalendar update?

**Comment by josemadev** [comment]
While they do not update the library you can use:
yarn add https://github.com/josemadev/fullcalendar-angular#c12c0753f0ce354f29ea8db1a3cc2a871bca380e

**Comment by irustm** [comment]
fixes in #269
