### ISSUE TITLE
[BUG] `eventResizableFromStart` or `eventStartEditable` seems to be not working.

### ISSUE THREAD

**Issue by fzs1994** [fullcalendar/fullcalendar-angular#273]
I've created an app for FullCalendar in which I want the events to be editable from both top and bottom end. Currently, I'm only able to drag slider from bottom to increase the event time from end. I've added both values for `eventResizableFromStart` or `eventStartEditable` as `true` but I'm not getting drag slider from top of the event, thus not able to drag and edit from top edge.

![Annotation 2020-02-05 134825](https://user-images.githubusercontent.com/10684213/73823515-70635c00-481e-11ea-9cdf-cd9a9c8cbaac.png)

Reproduction:
https://stackblitz.com/edit/angular-m1tlh2

**Comment by irustm** [comment]
I think it's a problem that needs to be voiced in fullcalendar repositories.
