### ISSUE TITLE
nowIndicator displays in wrong position in MatDialog modal

### ISSUE THREAD

**Issue by ricardofct** [fullcalendar/fullcalendar-angular#274]
Hi there, I think found an unexpted behavior.

I tryed create a component with calendar created dynamically, and this component is used in MatDialog. When we open that MatDialog the nowIndicator has a wrong position, you can see it [here](https://stackblitz.com/edit/angular-fullcalendar-dynamically-with-dialog-material)

If you compare the nowIndicator of the dialog with the background, you can see it in different positions, and if you select a cell the nowIndicator update to the expected time.

This happen with events too, if you select a cell and then click in "UPDATE EVENTS", you can see the event changing position.

**Comment by bfwg** [comment]
I'm running into the same problem in V5 and if you manually delay the load the position of the event will be correct.
```
  ngAfterViewInit() {
    setTimeout(() => {
      this.loadComponent();
    }, 1000);
  }
```
My guess is that the calendar is trying to load while the material dialog prompts and the size calculation is off.

Any updates on this? @ricardofct

**Comment by vuoriliikaluoma** [comment]
I had a similar problem with Scheduler in a Vuetify dialog.
Turned out to be the transition (animation) of the dialog that caused the problem.
The calendar was loading and calculating things with at certain width and then then the transition finished.
This caused the events to be offset from the correct time.
We solved this by just turning of the transition on that dialog.

**Comment by sdyachenko** [comment]
Even if I disable animation through NoopAnimationsModule, FullCalendar doesn't highlight the selected dates properly.
![ezgif-6-b83980468e](https://user-images.githubusercontent.com/22190617/150333904-5d93bf9b-b9f5-4ecc-aca7-f060d47ae4bb.gif)

The only way I found is just to call "render" of calendar API on setTimeout 250ms.

The calendar doesn't highlight the days properly without this timeout.
![ezgif-6-fe8816ef80](https://user-images.githubusercontent.com/22190617/150333952-b67afdd8-0281-4c29-ad57-41a38ef41668.gif)

**Comment by arshaw** [comment]
In response to the original issue, @bfwg's solution is the best idea.

At some point, FullCalendar will stop listening to window resizes to know when to readjust sizing (might use [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) instead). Until then, `Calendar::updateSize` must be called strategically to do this.

I assume @bfwg's workaround internally calls updateSize somehow
