### ISSUE TITLE
Blocker : Angular 9 upgrade

### ISSUE THREAD

**Issue by TejasCMehta** [fullcalendar/fullcalendar-angular#276]
### Bug Reports

![image](https://user-images.githubusercontent.com/5519037/74029358-86b21900-49d2-11ea-8e67-7876adaae435.png)

![image](https://user-images.githubusercontent.com/5519037/74029157-13100c00-49d2-11ea-9bf3-98ef42256404.png)

### Is your bug/feature applicable to the core project, without Angular?
`Not sure`

I upgraded my project from angular 8 to angular 9 and I got above issue while running project from `ng serve` command.

Can anyone help me in this as I have big updates in my project with some milestones.

#270 
@arshaw @irustm

**Comment by anisha1285** [comment]
i am facing the same issue . . .any updates ?

I upgraded my project from angular 8 to angular 9 and I got above issue while running project from ng build command.

**Comment by antoinepairet** [comment]
Please see https://github.com/fullcalendar/fullcalendar-angular/pull/275

**Comment by irustm** [comment]
Same issue #270
