### ISSUE TITLE
Resource Time Grid TypeError

### ISSUE THREAD

**Issue by actaruspd** [fullcalendar/fullcalendar-angular#277]
I istalled following package:
`"@fullcalendar/angular": "^4.3.1",
    "@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@fullcalendar/list": "^4.3.0",
    "@fullcalendar/resource-common": "^4.3.1",
    "@fullcalendar/resource-daygrid": "^4.3.0",
    "@fullcalendar/resource-timegrid": "^4.3.0",
    "@fullcalendar/timegrid": "^4.3.0",`

In the calendar.ts I set the plugin resourceTimeGridPlugin and the application works fine but I have an error in cosole:
`Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined`
This error refers to resource timegrid main.js (line 13).
`var ResourceCommonPlugin__default = 'default' in ResourceCommonPlugin ? ResourceCommonPlugin['default'] : ResourceCommonPlugin;`

**Comment by irustm** [comment]
Please make an example on stackblitz.
https://stackblitz.com/edit/fullcalendar-angular-demo?file=src%2Fapp%2Fapp.component.ts

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
