### ISSUE TITLE
Ionic Angular cannot select/drag/date click

### ISSUE THREAD

**Issue by butterfly-valley** [fullcalendar/fullcalendar-angular#282]
I cannot do all of the above actions on my fullcalendar which renders with no issues. I know it is a css issue on my side since the select/drag/date click are triggered by clicking on a certain element on the calendar which in my case is probably overflown/hidden by some other element.

I have tried creating a sample Ionic project on stackblitz but it does not load the css correctly hence I cannot reproduce it here. 

One thing I have noticed is that I can select all the text as shown on the screenshot below which is something I cannot do on the official demos which tells me there is something in my global css that is conflicting with fullcalendar's css settings. 

If someone could just point me to the exact html element that triggers the actions above I would probably be able to debug.

Thanks a lot in advance.

https://imgur.com/jN2ip5C

**Comment by irustm** [comment]
I think ionic overrides all dnd events.

Please see the answers about ionic https://github.com/fullcalendar/fullcalendar-angular/issues?utf8=%E2%9C%93&q=ionic

**Comment by butterfly-valley** [comment]
I have already tried all the solutions in the mentioned issues. I have also added a fullcalendar in app.compoment.html where I have commented out all ionic-related code and still continue with this issue.

**Comment by butterfly-valley** [comment]
Relevant code:

`                     <div style="overflow: auto!important;">
                                <full-calendar id="fullcalendar"
                                               (datesRender)="datesRender($event)"
                                               #fullCalendar
                                               [allDaySlot]="false"
                                               [events]="fullcalendarService.calendarEvents"
                                               [height]="options.height"
                                               [header]="options.header"
                                               [customButtons]="options.customButtons"
                                               [plugins]="options.plugins"
                                               [locale]="options.locale"
                                               [minTime]="options.minTime"
                                               [maxTime]="options.maxTime"
                                               (eventRender)="options.eventRender($event)"
                                               [eventTimeFormat]="options.eventTimeFormat"
                                               [showNonCurrentDates]="false"
                                               (loading)="options.loading($event)"
                                               displayEventEnd="false"
                                               (eventClick)="fullcalendarClick($event)"
                                               [visibleRange]="options.visibleRange"
                                               [validRange]="options.validRange"
                                               [defaultView]="'timeGridWeek'"
                                               (eventMouseEnter)="options.eventMouseEnter($event)"
                                               (eventMouseLeave)="options.eventMouseLeave($event)"
                                               (dateClick)="dateClick($event)"
                                               (eventDragStop)="options.eventDragStart($event)"
                                               [contentHeight]="'auto'"
                                               [selectable]="true"
                                ></full-calendar>
                                </div>`

**Comment by butterfly-valley** [comment]
Relevant code
>                      <div style="overflow: auto!important;">
                                <full-calendar id="fullcalendar"
                                               (datesRender)="datesRender($event)"
                                               #fullCalendar
                                               [allDaySlot]="false"
                                               [events]="fullcalendarService.calendarEvents"
                                               [height]="options.height"
                                               [header]="options.header"
                                               [customButtons]="options.customButtons"
                                               [plugins]="options.plugins"
                                               [locale]="options.locale"
                                               [minTime]="options.minTime"
                                               [maxTime]="options.maxTime"
                                               (eventRender)="options.eventRender($event)"
                                               [eventTimeFormat]="options.eventTimeFormat"
                                               [showNonCurrentDates]="false"
                                               (loading)="options.loading($event)"
                                               displayEventEnd="false"
                                               (eventClick)="fullcalendarClick($event)"
                                               [visibleRange]="options.visibleRange"
                                               [validRange]="options.validRange"
                                               [defaultView]="'timeGridWeek'"
                                               (eventMouseEnter)="options.eventMouseEnter($event)"
                                               (eventMouseLeave)="options.eventMouseLeave($event)"
                                               (dateClick)="dateClick($event)"
                                               (eventDragStop)="options.eventDragStart($event)"
                                               [contentHeight]="'auto'"
                                               [selectable]="true"
                                ></full-calendar>
                                </div>

**Comment by butterfly-valley** [comment]
Sorry to be insisting but I have not been able to sort this out. I have tried to create a calendar outside ion-router but the behaviour is the same.

**Comment by butterfly-valley** [comment]
Still have not figured what the issue is, any ideas?

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

May be related to this issue:

https://github.com/fullcalendar/fullcalendar/issues/4976
