### ISSUE TITLE
Calendar of undefined 

### ISSUE THREAD

**Issue by apoklyak** [fullcalendar/fullcalendar-angular#285]
Hello!

Sometimes I get this error: https://i.gyazo.com/e321dc74a0c12c8a067bbfba76466a73.png

It looks like the 'context' is undefined (https://i.gyazo.com/570a4c0706c5020f5ac96f2dfb24b748.png)

Do you know how to fix it?

**Comment by irustm** [comment]
please write about it in the main repository.
