### ISSUE TITLE
dblClick functionality is not working via eventlistner

### ISSUE THREAD

**Issue by Milanis1n1** [fullcalendar/fullcalendar-angular#286]
domEvent.el.addEventListener('dblclick', () => {
            this.schedulerEventDoubleClicked(domEvent.event);
 });

**Comment by irustm** [comment]
Hey! please add minimal reproducing in stackblitz, for example

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
