### ISSUE TITLE
How to install Rrule PLugin in Angular 8

### ISSUE THREAD

**Issue by WAGNERPFONSECA** [fullcalendar/fullcalendar-angular#289]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

### Is your bug/feature applicable to the core project, without Angular?
If so, use the main tracker: https://github.com/fullcalendar/fullcalendar/issues

(Please erase the above text and begin typing. Thanks!)

**Comment by irustm** [comment]
You can see this Demo with Angular8 and plugins:
https://stackblitz.com/edit/fullcalendar-angular-demo?file=src%2Fapp%2Fapp.component.html

```html
 [plugins]="options.plugins"
```

and in ts
```ts
 // add other plugins
      plugins: [dayGridPlugin, interactionPlugin, timeGridPlugin, resourceTimeGridPlugin]
```
