### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by mits87** [fullcalendar/fullcalendar-angular#290]
Hi, 

Can you add support for Angular 9? 
Currently when I'm trying do npm install I've got:

> npm WARN @fullcalendar/angular@4.4.1 requires a peer of @angular/core@>=7.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @fullcalendar/angular@4.4.1 requires a peer of @angular/common@>=7.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.

When I'm trying run the app I have those errors: 

> ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
>  - @fullcalendar/core/types/input-types
>  - @fullcalendar/core/datelib/env
>  - @fullcalendar/core/datelib/duration
>  - @fullcalendar/core/datelib/formatting
>  - @fullcalendar/core/datelib/date-range
>  - @fullcalendar/core/datelib/locale
>  - @fullcalendar/core/validation
>  - @fullcalendar/core/structs/event-source
> 

Thank you in advance.

**Comment by tlebreton** [comment]
Hi

You need to use the 4.4.5-beta version `@fullcalendar/angular@4.4.5-beta`

See the discussion in this PR [https://github.com/fullcalendar/fullcalendar-angular/pull/275](url)

**Comment by irustm** [comment]
Please update to @fullcalendar/angular@4.4.5-beta
