### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by rajaunleashed** [fullcalendar/fullcalendar-angular#293]
Here is the error log while hit npm run serve:ssr

```
var matchesMethod = Element.prototype.matches ||       
                        ^

ReferenceError: Element is not defined
    at D:\projects\yra\dist\server\main.js:141177:25       
    at Vz3n (D:\projects\yra\dist\server\main.js:141078:13)
    at Object.Vz3n (D:\projects\yra\dist\server\main.js:141080:2)
    at __webpack_require__ (D:\projects\yra\dist\server\main.js:20:30)
    at Module.UUxd (D:\projects\yra\dist\server\main.js:138834:76)
    at __webpack_require__ (D:\projects\yra\dist\server\main.js:20:30)
    at Object.sZXh (D:\projects\yra\dist\server\main.js:220458:12)
    at __webpack_require__ (D:\projects\yra\dist\server\main.js:20:30)
    at Object.gnUf (D:\projects\yra\dist\server\main.js:180589:12)
```

Dependencies are: 

```
dependencies": {
    "@angular/animations": "~8.2.13",
    "@angular/common": "~8.2.13",
    "@angular/compiler": "~8.2.13",
    "@angular/core": "~8.2.13",
    "@angular/forms": "~8.2.13",
    "@angular/platform-browser": "~8.2.13",
    "@angular/platform-browser-dynamic": "~8.2.13",
    "@angular/platform-server": "~8.2.13",
    "@angular/router": "~8.2.13",
    "@auth0/angular-jwt": "^3.0.0",
    "@fullcalendar/angular": "^4.3.1",
    "@fullcalendar/core": "^4.3.1",
    "@fullcalendar/daygrid": "^4.3.0",
    "@fullcalendar/interaction": "^4.3.0",
    "@fullcalendar/list": "^4.3.0",
    "@fullcalendar/moment": "^4.3.0",
    "@fullcalendar/timegrid": "^4.3.0",
```

**Comment by gitalvininfo** [comment]
Any updates for this? Having the same issue.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4784
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

If there is another issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by rajaunleashed** [comment]
Hi,

Thank you for answering, but its for Vuejs, I need it in angular 8

**Comment by gitalvininfo** [comment]
Hi @rajaunleashed 

Your problem is caused by the 'use strict' emitted by TypeScript. I've managed to solved this problem in Angular Universal when serving the application. 

Import it at server.ts and try to put it below zone.js import.

`const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync(path.join('.', 'browser', 'index.html')).toString();
Object.assign(global, domino.impl);
(global as any)['KeyboardEvent'] = domino.impl.Event;
const win = domino.createWindow(template);
global['window'] = win;
global['document'] = win.document;
`


You need first to install domino, fs, path via npm

I hope this will solve your problem

**Comment by acerix** [comment]
@rajaunleashed The issue is that SSR is not supported, adding that support should also get it working in Angular.

**Comment by rajaunleashed** [comment]
Hi @acerix I tried your code in server.ts but still the same error. See the error in the Screenshot https://prnt.sc/11kp43c

**Comment by omkarmhetar** [comment]
Facing the same issue , any updates on this issue?? Has anyone resolved this issue?
