### ISSUE TITLE
eventLimitClick not firing

### ISSUE THREAD

**Issue by manishdubeit** [fullcalendar/fullcalendar-angular#295]
Hii all

i need a click event listener when i click on n+ more event item,
in document there is an event listener for this i.e. eventLimitClick
but it is not working, have anyone faced this issue?

here is the my code

component.html file
![image](https://user-images.githubusercontent.com/38417244/78009984-73cb1d80-735f-11ea-815d-8ba9de358c13.png)

component.ts file
![image](https://user-images.githubusercontent.com/38417244/78009040-11bde880-735e-11ea-9939-07f5ed847bc7.png)

here is my package.json file

![image](https://user-images.githubusercontent.com/38417244/78009150-387c1f00-735e-11ea-9fe4-57143d532d9e.png)
please help

**Comment by manishdubeit** [comment]
Team any update

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
