### ISSUE TITLE
Missing side borders of calendar with adminLTE

### ISSUE THREAD

**Issue by pedroalvesr** [fullcalendar/fullcalendar-angular#297]
Hi,

I have an angular project version 7 (+), I'm using adminLTE 3, fullCalendar and I'm having trouble rendering the left and right edges of the calendar.

I am not able to manually adjust the calendar css to show the side borders.

What do I need to do to make the calendar borders render correctly?

Here is the image of the project that I am using css adminLTE3 together with fullCalendar.

![image](https://user-images.githubusercontent.com/22817118/78603679-eb50ef00-782e-11ea-8a96-f12bf8dfedc4.png)

Here, the link to the code that shares the problem: 
https://stackblitz.com/edit/fullcalendar-with-adminlte3

Thank you in advance.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I'm not sure why the borders are missing in your demo, they show as expected with default CSS:

https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/angular?file=/src/app/app.component.ts

Do you mean that including the CSS from adminLTE causes that issue?

**Comment by arshaw** [comment]
Something from adminLTE is causing this:
![Screen Shot 2022-12-09 at 4 35 41 PM](https://user-images.githubusercontent.com/56520/206799989-93192fb6-e03c-4503-b825-44ec02e79ead.png)
