### ISSUE TITLE
'dayHeaders' error with FC v5-beta2 on Angular 9

### ISSUE THREAD

**Issue by Sidewinder1138** [fullcalendar/fullcalendar-angular#299]
I could really use some help, sorry if I'm breaking any of the rules:

I'm trying to use FullCalendar v5 beta 2 with Angular 9. Try as I might (I've looked at every scrap of documentation and example code), I always get this error:

ERROR TypeError: Cannot read property '**dayHeaders**' of undefined
    at DayTableView.push.../../node_modules/@fullcalendar/daygrid/main.js.DayTableView.render (main.js:1057)
    at A (preact.module.js:1)
    at preact.module.js:1
    at x (preact.module.js:1)
    at x (preact.module.js:1)
    at b (preact.module.js:1)
    at A (preact.module.js:1)
    at preact.module.js:1
    at x (preact.module.js:1)
    at x (preact.module.js:1)

It's a slightly different but similar one for other calendar views.

I was previously using FC v4 without any problems.

**Comment by ArthurianX** [comment]
Same her @Sidewinder1138 - what was your solution ?

**Comment by JoniWanKenobi** [comment]
Have exactly the same problem and I can't seem to fix it. I created a component with the same code as the official example code and does the same error. @Sidewinder1138 @ArthurianX any progress?

**Comment by Sidewinder1138** [comment]
Well I'm happy it's not just me, but sorry you guys are having issues too!

I haven't found a fix yet. I will try and find some time today or tomorrow to try and investigate again.

**Comment by Sidewinder1138** [comment]
Maybe I can get a minimal example of the problem up and running to share here... that'd be a good start...

**Comment by JoniWanKenobi** [comment]
3am here in Madrid but finally I managed to fix it.... What I did: 1) delete node_modules folder, 2) delete package-lock.json (this is what I wasn't doing...), 3) npm cache clean --force, 4) npm install. 

I could not figure out exactly what was wrong, but resetting everything with the steps above did it for me. Hope it works for you too, good luck! @Sidewinder1138  @ArthurianX

**Comment by Sidewinder1138** [comment]
@JoniWanKenobi  I tried your suggestion just now, and it seems to have worked! I can see the FullCalendar instance now and I'm not getting any errors. Really appreciate your help!
Of course... it's troubling that this was needed but I guess it's a reminder that the whole node/npm dependency system is hopelessly broken. Oh well :)
Curious if this helps for @ArthurianX ?
