### ISSUE TITLE
slotLabelFormat not work resourceTimelineMonth 

### ISSUE THREAD

**Issue by jnmcuong** [fullcalendar/fullcalendar-angular#302]
I try to use slotLabelFormat to format but it not work

![image](https://user-images.githubusercontent.com/15194294/81290299-07e08100-9092-11ea-9c98-60b4366b2a7a.png)

The weekday is still only one character
![image](https://user-images.githubusercontent.com/15194294/81290414-39594c80-9092-11ea-9c44-47851bad46eb.png)

Thanks,
@jnmcuong

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

It seems to work as expected for me:

https://codepen.io/acerix/pen/NWxewNd?editors=001

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
