### ISSUE TITLE
Expose events as @Input() again (like in v4)

### ISSUE THREAD

**Issue by osmolo** [fullcalendar/fullcalendar-angular#303]
In v5, the component has only one input for all the options and I think this is a drawback for doing things the Angular way. I strongly prefer the v4 way of having everything as input or output, it's clearer and conforms better to the Angular pattern, by the way...

[options] should be used for static configuration properties that presumably didn't change during the lifespan of the component but events can change frequently and can be useful to have their input property expecially when using async pipe.

Here are two examples of (simplified) code taken from a project of mine that uses NGRX and where events can change from actions outside the calendar component (filtered by a search, added...).

Current v5 implementation:
```
template: <full-calendar *ngIf="(calendarOptions$ | async) as options" [options]="options"></full-calendar>
...

  private readonly calendarOptions = {
    plugins: [dayGridPlugin, timeGrigPlugin, interactionPlugin, listPlugin],
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
    },
    ...
  };

  ngOnInit() {
    this.calendarOptions$ = this.store.pipe(
      select(EventsSelectors.selectEvents),
      map(events => {
        const newEvents = events
          .map(event => ({
              id: event.id,
              title: event.title,
              date: event.dueDate.toISOString(),
              allDay: true,
              editable: true,
          }));

        return { ...this.calendarOptions, events: newEvents };
      })
    );
  }

```

Proposed implementation:
```
template: <full-calendar [options]"calendarOptions" [events]="events$ | async"></full-calendar>
...
  public readonly calendarOptions = {
    plugins: [dayGridPlugin, timeGrigPlugin, interactionPlugin, listPlugin],
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
    },
    ...
  };

  ngOnInit() {
    this.events$ = this.store.pipe(
      select(EventsSelectors.selectEvents),
      map(events => events.map(event => ({
              id: event.id,
              title: event.title,
              date: event.dueDate.toISOString(),
              allDay: true,
              editable: true,
          }))
      )
    );
  }
```

**Comment by blackholegalaxy** [comment]
Agreed. Having to change options object when updating the events is kind of messy. As stated by @osmolo we load our events through NGRX effects and rely heavily on our store to get updated and new events. We expect to be able to pass the events like:
`[events]="events$ | async"`

**Comment by efcoyote** [comment]
With the event handlers it's the same and the code gets a bit messy.
**Before**
```ts
(eventClick)="selectEvent($event.event)"

selectEvent(event: EventApi): void { 
  this.eventSelected.emit(event);
}
```

**After**
```ts
calendarOptions: CalendarOptions = {
  eventClick: this.selectEvent.bind(this)
}

selectEvent(info: { event: EventApi }): void { 
  this.eventSelected.emit(info.event);
}
```

Btw the event property is important but not [documented anymore](https://fullcalendar.io/docs/dateClick).

**Comment by andlewis** [comment]
At the very least, can we get any kind of documentation on how to hookup events in Angular with v5.0? It's pretty opaque right now unless you're using a static array.

**Comment by jasedwards** [comment]
In regards to this, is there any documentation that shows breaking changes?  I looked at change log and release tags, saw nothing so updated.  just had to back it out because it turns out this release is all breaking changes.

**Comment by jolle-c** [comment]
I found this really useful for my migration from V 4 to V 5.

https://fullcalendar.io/docs/upgrading-from-v4

HDB
Jolle

**Comment by stehag** [comment]
What's the current state of this? Is @irustm still working with the angular connector?

**Comment by irustm** [comment]
@arshaw what do you think about it? I'm ready to change the API, and go back to the old way.

**Comment by stehag** [comment]
@arshaw Please advice.

**Comment by MJomaa** [comment]
Yeah the Angular API for v4 looked much better

**Comment by stehag** [comment]
@irustm Please, you are the maintainer of the angular connector, clearly angular is not a priority or area of interest to Arshaw, what do you think? This is IMHO a blocker for upgrading to v5 for angular projects.

**Comment by irustm** [comment]
@stehag  I mostly only support the critical stuff in Angular, and want to contribute some other features . Arshaw does everything else. I'll try to coordinate these changes by mail with Arshaw, and I'll be sure to post in this thread.

**Comment by josegomez** [comment]
Is there an update on this issue? I can't seem to find a clean way to add events by modifying the event array. Can someone give me a workaround? I basically need to push/pop events into / out of an array in my app and I have had no luck.

The initial event shows, but the one below being pushed doesn't
```ts
calEvents:EventInput[]=[{title:'Test', allDay:true, date:'2021-03-24'}];

  calendarOptions: CalendarOptions = {
    initialView: 'timeGridWeek',
    businessHours: true,
    headerToolbar:{start:'title', center:'', end:'today dayGridDay timeGridWeek dayGridMonth prev,next'},
    buttonText: {
      day: 'day view',
      week: 'week view',
      month: 'month view'
    },
    events:this.calEvents
  };
  constructor() {

    setTimeout(()=>{
      console.log('Firing');
      this.calEvents.push({title:'Test 2', allDay:true, date:'2021-03-23',});
    },10000)

  }
```

**Comment by makkaronis4e** [comment]
honestly its imposible to work with this new way of inputs.

**Comment by jolle-c** [comment]
Not sure how a comment like yours is supposed to help you or anyone.

For the record, we have a fully functional implementation of FullCalendar working in Angular 11. Used for event and stage performance productions. Calendar under heavy use while planning, executing and evaluating the business.
Adding, editing, searching/filtering. All working nicely. So, no, I know first hand that it is not "impossible" to work with FullCalendar. My only unsolvable beef has been with the printing bug, and that will be solved in the upcoming release, I've been told. So support is working too.

/Jolle

> 28 mars 2021 kl. 14:21 skrev makkaronis4e ***@***.***>:
> 
> 
> honestly its imposible to work with this new way of inputs.
>

**Comment by brinehart** [comment]
I too am struggling with how to populate events coming from our server into the calendar. I have tried just about every way that has been mentioned in open and closed issues here and can't seem to get the events to render.

For clarity, I am using state management (Akita, but the same principal holds true for any of them, ngrx, etc) to select a slice of state that contains objects with the following signature:
```
id: string;
title: string;
start: string;
end: string;
```
The ideal angular way of doing dynamic events from the server would be:
`*.component.ts`
```
export class SomeComponent
[...]
events$: Observable<EventInput[]>;

ngOnInit() {
    this.events$ = this.store.select(selector);
}
```

`*.component.html`
```
  <full-calendar
    [options]="calendarOptions"
    [events]="events$ | async"
    #calendar
  ></full-calendar>
```

**Comment by arshaw** [comment]
This has been implemented in [v6.0.0-beta.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.3)

Docs: https://fullcalendar.io/docs/v6/angular#individual-inputs

It applies to `events`, `eventSources`, and `resources`.

If someone could take the [angular15 example project in the v6 branch](https://github.com/fullcalendar/fullcalendar-example-projects/tree/v6/angular15), copy it and make a separate new `angular15-ngrx` directory, then implement the event-adding with NgRx, the new `events` input, and `| async`, that would be INCREDIBLY helpful.

**Comment by arshaw** [comment]
If anyone could report whether these new changes meet their criteria, that'd be great.

**Comment by efcoyote** [comment]
I'm still working at the `angular15-ngrx` example project. I try to include all changes.

**Comment by efcoyote** [comment]
After selecting the correct target branch you can take a look. The binding of `events` is still a bit tricky. The `async` pipe will return `EventSourceInput | null` or `EventSourceInput | undefined | null` but the `@Input` expect just `EventSourceInput | undefined`. The `null` type is missing.

**Comment by arshaw** [comment]
@efcoyote thank you so much for making the example project!!! I've merged it into the v6 branch.

I've also addressed the `undefined|null` issue in [v6.0.0-beta.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.4). I've made a ticket [specifically for it](https://github.com/fullcalendar/fullcalendar-angular/issues/424)

**Comment by efcoyote** [comment]
You're welcome, thanks for your efforts.

**Comment by arshaw** [comment]
Release in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
