### ISSUE TITLE
EventInput extendedProps is of object type instead of any

### ISSUE THREAD

**Issue by cyrilfr** [fullcalendar/fullcalendar-angular#304]
I'm using the `extendedProps` property of `EventInput` but the TypeScript transpiler says that all the custom properties I added to the `extendedProps` do not exist on type 'object'.

**Comment by arshaw** [comment]
hey @cyrilfr, could you try using the v5-beta3 release? the overall API has changes ([upgrade guide](https://fullcalendar.io/docs/v5/upgrading-from-v4)), but this particular issue has been fixed

**Comment by arshaw** [comment]
the new release candidate should have extendedProps defined as a better hash-like type now
