### ISSUE TITLE
calendar.prev() doesn't work for the 4 week view

### ISSUE THREAD

**Issue by marektoman** [fullcalendar/fullcalendar-angular#309]
### Working example
https://stackblitz.com/edit/angular-ivy-umrcdp
https://angular-ivy-umrcdp.stackblitz.io

### Steps to reproduce
1. Click the right arrow button a few times
2. Click the left arrow button at least twice

### Expected result
The calendar moves to the previous date range.

### Actual result
The calendar date range doesn't change.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4678
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
