### ISSUE TITLE
Module '"@fullcalendar/core"' has no exported member 'CalendarOptions'.

### ISSUE THREAD

**Issue by agiratech-manigandan** [fullcalendar/fullcalendar-angular#310]
![image](https://user-images.githubusercontent.com/17978822/83439828-81854800-a461-11ea-82bb-a4cb53982209.png)

![image](https://user-images.githubusercontent.com/17978822/83439956-b2657d00-a461-11ea-89e8-01938f991b02.png)

### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

### Is your bug/feature applicable to the core project, without Angular?
If so, use the main tracker: https://github.com/fullcalendar/fullcalendar/issues

(Please erase the above text and begin typing. Thanks!)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the error? Would really appreciate it because the time saved reproducing will be time spent fixing.

It may be that not all modules were updated, clearing package cache may help.

**Comment by muneebahmad0600** [comment]
Hi there, I am having the same problem. I followed the instruction of the documentation. [](https://fullcalendar.io/docs/angular).

**Comment by agiratech-manigandan** [comment]
> Hi there, I am having the same problem. I followed the instruction of the documentation.
> https://fullcalendar.io/docs/angular

Here, I have added "skipLibCheck": true in the tsconfig.json file.
I am not sure this is a way to solve this issue.

![image](https://user-images.githubusercontent.com/17978822/92250428-18dabb00-eee9-11ea-8b2c-06dc6c04c364.png)
