### ISSUE TITLE
Drag & drop feature does not work for the first time

### ISSUE THREAD

**Issue by ShqipeGit** [fullcalendar/fullcalendar-angular#312]
![isWithinClipping](https://user-images.githubusercontent.com/57507881/84137064-71b2c880-aa4c-11ea-9590-0f5e90b95570.png)

Hello,
this is the error that i am facing when i try to drag and drop event, but this only happens for the first time of dragging then the others drag and drops works perfectly.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
