### ISSUE TITLE
V5 Beta Support

### ISSUE THREAD

**Issue by dreadnautxbuddha** [fullcalendar/fullcalendar-angular#314]
I just found out that V5 beta has already [been out](https://fullcalendar.io/blog/2020/04/v5-beta-released) and I'd like to ask whether the Angular wrapper will support it anytime soon?

**Comment by acerix** [comment]
The Angular component has v5 beta releases at the same time, here are the docs for v5:

https://fullcalendar.io/docs/v5/angular

**Comment by dreadnautxbuddha** [comment]
Oh, didn't see that. Thanks @acerix
