### ISSUE TITLE
Width not adjusting to full screen

### ISSUE THREAD

**Issue by jamesamuel** [fullcalendar/fullcalendar-angular#319]
Calendar does not always expand to full width of screen. I am not dynamically adjusting screen sizes, just navigating to and from the component that contains the calendar.

Using: `"@fullcalendar/angular": "^5.0.0",
    "@fullcalendar/timegrid": "^5.0.0",`

https://imgur.com/8OGKcee

This seems to fix the issue: 
`  .fc-col-header,
    .fc-timegrid-body {
        width: 100% !important;
    }`

 `.fc-timegrid-body {
        table {
            width: 100% !important;
        }
    }`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by rattkin** [comment]
> This seems to fix the issue:
> ` .fc-col-header, .fc-timegrid-body { width: 100% !important; }`
> `.fc-timegrid-body { table { width: 100% !important; } }`

This does not work for me. Is your solution still working for you?

I think the expand works fine when there are event, but when the calendar is empty, the width is mismatched.

**Comment by rattkin** [comment]
my solution:
setTimeout(() => {
      this.calendarComponent.getApi().updateSize();
});

**Comment by mabe-at** [comment]
Hi!
With ::ng-deep you can set the calendar's width to 100% in your component.

something like this:

```
::ng-deep {
    table.fc-col-header, .fc-scroller > div, .fc-scroller > div > table {
        width: 100% !important;
    }
}
```
More about style encapsulation at https://angular.io/guide/component-styles

**Comment by archanavpatil** [comment]
In React fullcalendar (version 5), I could not call the render or rerender method. Also forceful updateSize() method doesn't work for me.

FullCalendar automatically updates size when it listens to window resize events. I just the trigger resize event when the calendar tab is visible with some delay.
Refer following code
```
setTimeout(() => window.dispatchEvent(new Event('resize')), 500)
```
I am using react here, it may be useful to other frameworks.

**Comment by yaberkane05** [comment]
still having this problem, any news on this ?

**Comment by ShellyRiver** [comment]
I solved this by adding

.content {
    height: 100% !important;
}
.fc-col-header, .fc-timegrid-body { 
    width: 100% !important; 
    height: 100% !important;
}
.fc-scrollgrid-sync-table { 
    width: 100% !important; 
    height: 100% !important;
} 
.fc-daygrid-body {
    width: 100% !important;
    height: 100% !important;
}
.fc-daygrid-body-balanced {
    width: 100% !important;
    height: 100% !important;
}

**Comment by ShellyRiver** [comment]
I inspected my elements and checked where it started to be not full screen. Maybe you can try this. 
![image](https://user-images.githubusercontent.com/109195884/207763943-9082d95f-0210-4d9b-9a8c-61715fc1c281.png)

**Comment by vimal1824** [comment]
When I expand the side menu the calendar is getting hidden, but after clicking on any day it is adjusting correctly, please see this link [https://stackoverflow.com/questions/74809615/react-full-calendar-views-are-not-adjusting-their-width](url)

**Comment by vimal1824** [comment]
> .content {
> height: 100% !important;
> }
> .fc-col-header, .fc-timegrid-body {
> width: 100% !important;
> height: 100% !important;
> }
> .fc-scrollgrid-sync-table {
> width: 100% !important;
> height: 100% !important;
> }
> .fc-daygrid-body {
> width: 100% !important;
> height: 100% !important;
> }
> .fc-daygrid-body-balanced {
> width: 100% !important;
> height: 100% !important;
> }

This worked perfectly for the Month view, thanks :)
for week, day views i used the below code:

table {
  width: 100% !important;
  height: 100% !important;
}
