### ISSUE TITLE
node_modules/@fullcalendar/common/main.d.ts(812,9): error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by LuisGustavoVMSNew** [fullcalendar/fullcalendar-angular#323]
eroo TS1086 nao consigo resolver

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by FranceschiniGiulia** [comment]
@LuisGustavoVMSNew Were you able to solve the problem?
