### ISSUE TITLE
Problem with starting demo application

### ISSUE THREAD

**Issue by irekBudzowski** [fullcalendar/fullcalendar-angular#325]
### Bug Reports
There is a problem with starting demo application.
To reproduce it, simply clone the repo, run `npm install` and `npm start`
Current behavior: error in terminal
Expected behavior: working demo

**Comment by irekBudzowski** [comment]
I created PR with solution to the problem
https://github.com/fullcalendar/fullcalendar-angular/pull/326

**Comment by acerix** [comment]
It tried running these commands for the example project and didn't get any error:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular#installation

Are you doing the same and what is the error message?

**Comment by irekBudzowski** [comment]
@acerix Thanks, I've checked today one more time. After restarting my machine the problem gone. I closed the PR.
