### ISSUE TITLE
Support for Angular 10

### ISSUE THREAD

**Issue by andrejm7** [fullcalendar/fullcalendar-angular#328]
npm WARN @fullcalendar/angular@5.1.0 requires a peer of @angular/common@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fullcalendar/angular@5.1.0 requires a peer of @angular/core@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fullcalendar/angular@5.1.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

**Comment by arshaw** [comment]
there doesn't seem to be any breaking changes that affect the FullCalendar connector:

https://next.angular.io/guide/updating-to-version-10#new-breaking-changes

So, I'll make the semver string `"angular": "9 - 10"`

**Comment by somq** [comment]
Hi there,

Following the [official doc](https://fullcalendar.io/docs/angular) steps I'm having this error running fullcalendar under angular 10
Here are the logs:

Log

```log
ERROR in node_modules/@fullcalendar/angular/lib/fullcalendar.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (@fullcalendar/angular) which declares FullCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    2 export declare class FullCalendarModule {
```

```log
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.4
Node: 12.14.0
OS: linux x64

Angular: 10.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cli                      10.0.4
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
```

**Comment by NerdyB713** [comment]
Any eta on this?

**Comment by guidopontet** [comment]
It doesn't work on Angular 10

```
ERROR in src/app/pages/dashboard/appointments/appointments.component.ts:8:40 - error TS2307: Cannot find module '@fullcalendar/core/Calendar' or its corresponding type declarations.

8 import Calendar, { DateClickApi } from '@fullcalendar/core/Calendar';
                                         
```

**Comment by nikoslyk2093** [comment]
can i make it to work before you update it for angular 10?

**Comment by arshaw** [comment]
this is in the works: https://github.com/fullcalendar/fullcalendar-angular/pull/336

**Comment by godly-devotion** [comment]
@arshaw Are there any updates regarding this? FullCalendar is the only package preventing us from upgrading to Angular 10

**Comment by andrejm7** [comment]
we are also waiting for a solution.

let's go fullcalendar time.

**Comment by arshaw** [comment]
I'm trying to merge+release this today but there's a build problem holding me up. If anyone has insight, please comment on the PR's thread

https://github.com/fullcalendar/fullcalendar-angular/pull/336#issuecomment-686565535

**Comment by arshaw** [comment]
v5.3.1 has been released. it has angular 10 support! thanks @irustm !

**Comment by techBeck03** [comment]
I'm still getting the following error when I try to run on angular `10` using fullcalendar version `5.3.1`

`Property 'rerenderEvents' does not exist on type 'Calendar'`

Anybody know how to resolve this?

Thanks
