### ISSUE TITLE
add "slot" support (with content projection?)

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-angular#330]
Similar how the Vue component [allows scoped-slots](https://fullcalendar.io/docs/upgrading-from-v4#vue-connector) to affect the rendering of content within the calendar, it'd be nice to have this functionality for the angular connector.

Is [multi-slot content projection](https://blog.angular-university.io/angular-ng-content/#multislotcontentprojection) the way to do it?

**Comment by arshaw** [comment]
@irustm, do you have any opinion on this?

**Comment by irustm** [comment]
great idea!

I think we should use the usual `template`, not `ng-content`

```html
<full-calendar>
   <ng-template ng-event-template let-arg="arg">
        <b>{{ arg.timeText }}</b>
        <i>{{ arg.event.title }}</i>
   </ng-template>
</full-calendar>
```

then add directive: 

```ts
@Directive({ selector: '[ng-event-template]' })
export class NgEventTemplateDirective {
    constructor(public template: TemplateRef<any>) { }
}
```

and gets this template in fullcalendar component

```ts
@ContentChild(NgEventTemplateDirective, { read: TemplateRef })
eventTemplate: TemplateRef<any>;

```


write to me if you're planning to implement =)

**Comment by arshaw** [comment]
wow that's really interesting! if this ticket gets enough likes, we should start building. but please hold off for now.

**Comment by arshaw** [comment]
i didn't realize there's already a ticket for this:
https://github.com/fullcalendar/fullcalendar-angular/issues/204
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

@irustm , I'll contact you over email about this

**Comment by kovalforpublic** [comment]
I think this question could be reopened, if you consider it like "adding slot template to customize how empty slots (with no events) are rendered"). 
 For example, I would like to have direct access to empty slots in otrder to implement some specific drag and drop logic.
