### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by joe991** [fullcalendar/fullcalendar-angular#332]
Running the FullCalendar Angular Connector with SSR (during compilation, not runtime) results in an error similar to other 3rd party libraries, which are mostly solved by using domino. This is unfortunately not the case.

`ReferenceError: window is not defined
    at Module../node_modules/@fullcalendar/core/vdom.js`

Here is my dependencies from package.json:

`"@angular/animations": "^10.0.4",
    "@angular/cdk": "^10.1.0",
    "@angular/compiler": "^10.0.4",
    "@angular/core": "^10.0.4",
    "@angular/forms": "^10.0.4",
    "@angular/platform-browser": "^10.0.4",
    "@angular/platform-browser-dynamic": "^10.0.4",
    "@angular/platform-server": "^10.0.4",
    "@angular/router": "^10.0.4",
    "@angular/service-worker": "^10.0.4",
    "@auth0/auth0-spa-js": "^1.11.0",
    "@fullcalendar/angular": "^5.1.0",
    "@fullcalendar/daygrid": "^5.1.0",
    "@gorniv/ngx-universal": "^2.2.2",
    "@nguniversal/express-engine": "^10.0.1",
    "@ngx-gallery/core": "^5.0.0-beta.0",
    "@ngx-gallery/gallerize": "^5.0.0-beta.0",
    "@ngx-gallery/lightbox": "^5.0.0-beta.0",
    "auth0-lock": "^11.25.1",
    "cookie-parser": "^1.4.5",
    "debug": "^4.1.1",
    "domino": "^2.1.6",
    "express": "^4.17.1",
    "firebase": "^7.16.1",
    "fullcalendar": "^5.1.0",
    "g": "^2.0.1",
    "localstorage-polyfill": "^1.0.1",
    "masonry-layout": "^4.2.2",
    "material-design-icons": "^3.0.1",
    "ng-click-outside": "^6.0.0",
    "ng-lazyload-image": "^8.0.1",
    "ngx-cookie-service": "^3.0.4",
    "ngx-infinite-scroll": "^9.0.0",
    "ngx-lightbox": "^2.2.0",
    "ngx-masonry": "^10.0.3",
    "ngx-webstorage": "^6.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "uuid": "^8.2.0",
    "zone.js": "~0.10.3"`

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4784
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by joe991** [comment]
Unfortunately the nature of the mentioned ticket does not fully represent the errors that occur when using Angular Universal, which is why a premature closing of this ticket does not suffice IMO.

**Comment by acerix** [comment]
It sounds like the issue is that SSR is not supported which that issue covers.

If there is another issue specific to Angular, please provide a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
