### ISSUE TITLE
How to create fullcalendar with angular 10 in child module.

### ISSUE THREAD

**Issue by pavanarela** [fullcalendar/fullcalendar-angular#333]
Issue:
![Selection_017](https://user-images.githubusercontent.com/66160454/88290283-23b00680-cd14-11ea-868a-bd408e36d013.png)

The files are as follows:
**1. full-cal.component.html**
<full-calendar [options]='calendarOptions'></full-calendar>

**2. full-cal.component.ts**

import { Component, OnInit } from '@angular/core';
import { CalendarOptions, DateSelectArg, EventClickArg, EventApi } from '@fullcalendar/angular';
@Component({
  selector: 'app-full-cal',
  templateUrl: './full-cal.component.html',
  styleUrls: ['./full-cal.component.css']
})
export class FullCalComponent implements OnInit {
  calendarVisible = true;
  calendarOptions: CalendarOptions = {
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
    },
    initialView: 'dayGridMonth',
    //initialEvents: INITIAL_EVENTS, // alternatively, use the `events` setting to fetch from a feed
    weekends: true,
    editable: true,
    selectable: true,
    selectMirror: true,
    dayMaxEvents: true,
    select: this.handleDateSelect.bind(this),
    eventClick: this.handleEventClick.bind(this),
    eventsSet: this.handleEvents.bind(this)
    /* you can update a remote database when these fire:
    eventAdd:
    eventChange:
    eventRemove:
    */
  };
  currentEvents: EventApi[] = [];

  handleCalendarToggle() {
    this.calendarVisible = !this.calendarVisible;
  }

  handleWeekendsToggle() {
    const { calendarOptions } = this;
    calendarOptions.weekends = !calendarOptions.weekends;
  }

  handleDateSelect(selectInfo: DateSelectArg) {
    const title = prompt('Please enter a new title for your event');
    const calendarApi = selectInfo.view.calendar;

    calendarApi.unselect(); // clear date selection

    if (title) {
      calendarApi.addEvent({
        title,
        start: selectInfo.startStr,
        end: selectInfo.endStr,
        allDay: selectInfo.allDay
      });
    }
  }
  handleEventClick(clickInfo: EventClickArg) {
    if (confirm(`Are you sure you want to delete the event '${clickInfo.event.title}'`)) {
      clickInfo.event.remove();
    }
  }
  handleEvents(events: EventApi[]) {
    this.currentEvents = events;
  }
  createEventId() {
    return 1;
  }
  constructor() { }
  ngOnInit() {
  }
}

**3. full-cal.module.ts**

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FullCalComponent } from './full-cal.component';
import { FullCalendarModule } from '@fullcalendar/angular';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import listPlugin from '@fullcalendar/list';
import interactionPlugin from '@fullcalendar/interaction';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { ComponentsModule } from '../../components/components.module';
import { SharedComponentsModule } from '../shared-components.module';
import { AppRoutingModule } from '../../app-routing.module';

FullCalendarModule.registerPlugins([
  dayGridPlugin,
  timeGridPlugin,
  listPlugin,
  interactionPlugin
]);

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    BrowserModule,
    HttpClientModule,
    FullCalendarModule
  ],
  declarations: [FullCalComponent]
})
export class FullCalModule { }

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by pavanarela** [comment]
**Note:** I am using full calendar version "5.1.0".
Run these npm:
npm i @fullcalendar/angular
npm i @fullcalendar/daygrid
npm i @fullcalendar/timegrid
npm i @fullcalendar/list
npm i @fullcalendar/interaction

**This the app folder inside "src" folder of angular 10 project.**
[app.zip](https://github.com/fullcalendar/fullcalendar-angular/files/4970834/app.zip)

Thanks
@acerix

**Comment by acerix** [comment]
Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) as described on that page (eg. on strackblitz).  

There is also an open issue for Angular 10 support:
https://github.com/fullcalendar/fullcalendar-angular/issues/328
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
