### ISSUE TITLE
Events Not working in Angular 9

### ISSUE THREAD

**Issue by iamakashaher** [fullcalendar/fullcalendar-angular#334]
Hello,

I've added fullcalendar in my angular 9 application, where UI can render properly, but my events do not work.
1. I've done lazy loading and added this 2 modules in my module.ts file

```
FullCalendarModule.registerPlugins([ // register FullCalendar plugins
  dayGridPlugin,
  interactionPlugin
]);
```

my .HTML code

```
 <full-calendar #fullcalendar (dateClick)="eventClick($event)"></full-calendar>
```

.ts file

```
@ViewChild('fullcalendar') fullcalendar: FullCalendarComponent;

calendarOptions: CalendarOptions = {
    initialView: 'dayGridMonth',
    plugins: [dayGridPlugin, interactionPlugin],
  };
```
I also tried adding interaction plugin in ngOnInit within options, but it didn't work for me.

Please find attached screenshot for brief:

![Screenshot from 2020-07-25 16-42-03](https://user-images.githubusercontent.com/44964180/88455787-f9865200-ce95-11ea-99ff-40874c309797.png)

![Screenshot from 2020-07-25 16-41-54](https://user-images.githubusercontent.com/44964180/88455785-f4290780-ce95-11ea-9973-ac07b310a6f1.png)

![Screenshot from 2020-07-25 16-44-33](https://user-images.githubusercontent.com/44964180/88455806-381c0c80-ce96-11ea-9f4f-a92a81e65828.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
