### ISSUE TITLE
Angular Material Theme

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [fullcalendar/fullcalendar-angular#335]
### Feature Requests
I can't find a way to assign the Angular Material Design theme to fullcalendar.
Only standard and bootstrap is available.
This really looks bad and didn't match to the rest of the Angular Material components.

Please tell us, how to modify or use Angular Material theme within fullcalendar component.

Thanks

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5127
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

You could try a 3rd party bootstrap theme like "bootstrap-material-design":

https://fullcalendar.io/docs/bootstrap-theme#3rd-party-bootstrap-themes

Or making a custom theme as was done here:

https://github.com/fullcalendar/fullcalendar/issues/2836
