### ISSUE TITLE
Terrible performance issue with lots of events

### ISSUE THREAD

**Issue by martijnhiemstra** [fullcalendar/fullcalendar-angular#345]
I am using version 5.0.0 of @fullcalendar/angular and I first tested it with a few events and that works perfectly. However a client of mine is now using it and they have planned about 100 events in a week and the performance is an absolute disaster. It is so bad that in all browsers I get an warning that it takes so long that they all want to stop the script. This is my configuration:

```
this.calendarOptions = {
locales: [nlLocale, enLocale],
weekNumbers: true,
nowIndicator: true,
headerToolbar: {
  left: 'prev,next today',
  center: 'title',
  right: 'resourceTimelineWeek,resourceTimelineDay'
},
initialView: 'resourceTimelineWeek',
dateClick: this.onDateClick,
validRange: {
  start: moment().subtract(1, 'months').format("YYYY-MM-DD")
},
weekends: true,
editable: true,
eventResourceEditable: true,
selectable: true,
eventOverlap: true,
selectMirror: true,
dayMaxEvents: true,
height: '820px',
droppable: true,
slotMinTime: '00:00',
slotMaxTime: '23:00',
slotDuration: '00:15:00',
resourceAreaHeaderContent: 'People',
resources: resources,
events: [],
eventDidMount: function (info) {
},
eventMouseEnter: eventEnter => {
},
eventMouseLeave: eventLeave => {
},
eventClick: eventClick => {
  this.onEventClick(eventClick); // Call custom code
},
select: selectionInfo => {
  this.handleDateSelect(selectionInfo); // Call custom code
},
eventDrop: eventDrop => {
  this.handleEventDrop(eventDrop); // Call custom code
},
datesSet: (dateInfo) => {
  this.search(dateInfo); // Call custom code
}
};
```

**Comment by martijnhiemstra** [comment]
I found out what the problem is. One of the events had a null end date. This caused the problem. I would be nice if there was some warning about this. For example console.log('Event with name has a null end date') and that the end date is set to the end of the calendar view.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by weilies** [comment]
u may try mine. terribly slow https://codesandbox.io/s/sb-fullcal-a4-u69kq

**Comment by maximeburri** [comment]
Hello @weilies. It seems that we have the same problem, but unfortunately the codesandbox link doesn't work. Could you give us another link so that we can test it and check if we have the same issue?
