### ISSUE TITLE
angular fullcalendar background events

### ISSUE THREAD

**Issue by voidbrain** [fullcalendar/fullcalendar-angular#347]
Vanilla Fullcalendar has a bgEventClick event that is triggered when a background event is clicked.
How can I use that on fullcalendar/angular projects?

Here the example: https://stackblitz.com/edit/angular-playground-gbxbtm?file=app%2Fapp.component.ts
event marked with: **display = background** is missing and **bgEventClick** is never triggering

_Originally posted by @voidbrain in https://github.com/fullcalendar/fullcalendar-angular/issues/346#issuecomment-717807162_

**Comment by acerix** [comment]
As I explained in your other issue, there is no `bgEventClick`.

**Comment by voidbrain** [comment]
I was pretty sure I found an event for them. So ok... 
but why fullcalendar does not shows events with "display background"? 
They are totally missing from the day cell

**Comment by voidbrain** [comment]
'  Also background events don't show in month view unless they are "allDay" (no time of day). '
That's why I was not able to see them.

Thank you. 
I don't know where I found bgEventClick, no problem If there is no a specific event as long as I can get the event from normal eventClick.
