### ISSUE TITLE
Angular 10 - "...FullCalendarComponent has not been processed correctly by ngcc, or is not compatible with Angular Ivy"

### ISSUE THREAD

**Issue by TeamEV** [fullcalendar/fullcalendar-angular#348]
ng version:

Angular CLI: 10.1.7
Node: 12.18.4
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cdk                    10.2.5
@angular/cli                    10.1.7
@angular/material               10.2.5
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.3

Deps:

"dependencies": {
    "@angular/animations": "~10.1.3",
    "@angular/cdk": "^10.2.5",
    "@angular/common": "~10.1.3",
    "@angular/compiler": "~10.1.3",
    "@angular/core": "~10.1.3",
    "@angular/forms": "~10.1.3",
    "@angular/material": "^10.2.5",
    "@angular/platform-browser": "^10.1.6",
    "@angular/platform-browser-dynamic": "~10.1.3",
    "@angular/router": "~10.1.3",
    "@fullcalendar/angular": "^5.3.1",
    "@fullcalendar/core": "^5.3.1",
    "@fullcalendar/daygrid": "^5.3.2",
    "@fullcalendar/interaction": "^5.3.1",
    "@fullcalendar/timegrid": "^5.3.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },

After installing the fullcalendar packages and importing them into the app.module.ts stated by the documentation.
I retrieve the following error after running ng serve:

![image](https://user-images.githubusercontent.com/73646466/97569844-a61d2600-19e7-11eb-886e-68df9b2c608a.png)

Already tried adding ""postinstall": "ngcc"" in package.json and reinstalling but same error.

Advice is appreciated.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the error? Would really appreciate it because the time saved reproducing will be time spent fixing.

You can use the example project as a starting point:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular
