### ISSUE TITLE
Cannot access API from FullCalendarComponent which is undefined

### ISSUE THREAD

**Issue by jaylordibe** [fullcalendar/fullcalendar-angular#350]
ERROR TypeError: Cannot read property 'getApi' of undefined

HTML
```
<full-calendar #fullCalendar [options]="calendarOptions"></full-calendar>
```

COMPONENT
```
calendarOptions: CalendarOptions = {
    initialView: 'dayGridMonth',
    plugins: [dayGridPlugin, interactionPlugin],
    headerToolbar: {
        left: 'title',
        center: '',
        right: 'previousMonth,nextMonth'
    },
    customButtons: {
        previousMonth: {
            text: 'Previous',
            icon: 'chevron-left',
            click: this.handlePreviousMonthClick
        },
        nextMonth: {
            text: 'Next',
            icon: 'chevron-right',
            click: this.handleNextMonthClick
        }
    }
}

@ViewChild('fullCalendar') fullCalendarComponent: FullCalendarComponent;

ngAfterViewInit(): void {
    console.log(this.fullCalendarComponent); // undefined
    this.calendarApi = this.fullCalendarComponent.getApi();
}

handlePreviousMonthClick(): void {
    this.calendarApi.prev();
    // TODO: Implement handlePreviousMonthClick() function...
}

handleNextMonthClick(): void {
    this.calendarApi.next();
    // TODO: Implement handleNextMonthClick() function...
}
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by jaylordibe** [comment]
@acerix Please see this demo. [https://angular-ivy-fullcalendar.stackblitz.io](url)

**Comment by acerix** [comment]
Thanks, confirmed. I could not find a way to access the API in those callbacks, maybe the example code in the docs needs an update:

https://fullcalendar.io/docs/angular#calendar-api

**Comment by irustm** [comment]
maybe it has something to do with https://github.com/fullcalendar/fullcalendar-angular/issues/305#issuecomment-732137736.

**Comment by arshaw** [comment]
@jaylordibe, you need to bind the handlers to `this`. Mentioned briefly here:
https://fullcalendar.io/docs/angular#props-and-emitted-events

updated repro:
https://stackblitz.com/edit/angular-ivy-fullcalendar-8q6l5y?file=src%2Fapp%2Fapp.component.ts
