### ISSUE TITLE
Change dependencies to support Angular 11

### ISSUE THREAD

**Issue by altarasyuk** [fullcalendar/fullcalendar-angular#351]
Angular 11 is currently not supported by 5.4.0.

**Comment by irustm** [comment]
https://github.com/fullcalendar/fullcalendar-angular/pull/352

**Comment by adrian-heath** [comment]
Is there any progress on this.  Currently fullcalendar-angular is the only dependency holding us back from updating to angular 11.

**Comment by DILEEP-YADAV** [comment]
Angular 11 is currently not supported by 5.4.0.
Following issue

![image](https://user-images.githubusercontent.com/8583769/102470133-9af68600-4079-11eb-96c9-312b9e0000ab.png)

**Comment by arshaw** [comment]
Angular 11 support has been released in v5.5.0. Sorry for the wait. I was intending to batch all changes, angular AND core, into a single release. In the future I won't do this, I'll just release angular updates ad-hoc if they are independent of the core.

**Comment by jlavric** [comment]
Big thanks!!
