### ISSUE TITLE
fullcalendar-example-projects/angular showing whitescreen for IE 11

### ISSUE THREAD

**Issue by felixxs** [fullcalendar/fullcalendar-angular#353]
Hi, 
I tried the  example project for FullCalendar and Angular from [https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular](url) - after building and running the example on IE 11 only a white screen was shown (no errors in browsers console). Everything is working fine when running in Google Chrome. 

The Issue can be reproced by following the instructions in the  [https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular](url) README.

Thank you in Advance.

**Comment by arshaw** [comment]
I'm getting the same problem, a blank screen in IE11. Screenshot of IE11 and Edge side-by-side:

![Screen Shot 2021-06-02 at 3 08 09 PM](https://user-images.githubusercontent.com/56520/120538396-75093780-c3b4-11eb-9552-9d9add13e9ec.png)

@acerix , do you have any ideas?

**Comment by arshaw** [comment]
I was able to fix this by modifying the example project. There seems to be no problem with the @fullcalendar/angular package.

If you set target:es5 in the tsconfig , it fixes:

https://github.com/fullcalendar/fullcalendar-example-projects/commit/214463bf3a48ecd222688a75f55dc100903d4610
