### ISSUE TITLE
Weekday labels wrong in month grid view after changing month

### ISSUE THREAD

**Issue by MikeChuckRoast** [fullcalendar/fullcalendar-angular#354]
I installed fullcalendar 5.5.0 plus angular package for Angular 9.1.13. In the month grid view, when I switch to a different month, the weekday labels all shift by 2 days so that the week now starts with Tuesday. However, the grid does not reflect this, so all of the labels are incorrect. 

Demo in stackblitz here:
https://stackblitz.com/edit/full-calendar-bug?file=src/app/app.component.html

Example screen shot for today:
![image](https://user-images.githubusercontent.com/33348493/103439167-90ef8e00-4c08-11eb-9a77-03d9b6d08bc8.png)

Reproduce by clicking the arrow to scroll forward a month, then click back to return. The problem goes away temporarily if I switch to week view and back to month; but then as soon as you scroll the month, the problem returns.

**Comment by acerix** [comment]
Thanks for the demo but I don't see the same on my side,  I click "month", then ">" to go forward a month, then "<" to go back a month and the labels always start with Sunday.  

Which browser do you see the issue in?  Let me know if I missed something.

**Comment by MikeChuckRoast** [comment]
I just checked the StackBlitz link, and it appears to be fine for me as well. However, I still see the issue in my actual application (https://rides.downrivercycling.org/calendar). Can you confirm you see the issue on that site? It had reproduced for me in StackBlitz originally as that's where the screen shot came from.

**Comment by acerix** [comment]
Yes, I also see the issue in your app, although it's hard to tell what the difference is, I wasn't able to reproduce the same in StackBlitz.

**Comment by MikeChuckRoast** [comment]
I can take another shot at stripping down my application code so it's reproducible. Unless you want to just try it with my full application. It shouldn't be just a build issue, because the problem occurs when I run locally and the deployed version, and the deployed version is built independently from the same code.

**Comment by acerix** [comment]
A stipped down reproduction would be appreciated, the time saved reproducing will be time spent fixing.

**Comment by MikeChuckRoast** [comment]
Sorry I left this hanging for so long. I'm a bit stumped, because stackblitz example seems to be the only thing that does work. The problem exists for me locally, and when I deploy to my server. I even did a completely clean build on a different computer, and I still see the problem. Can you please try cloning this locally to see if it reproduces for you: 
https://github.com/MikeChuckRoast/fullcalendar-bug

**Comment by Rafaelz2516** [comment]
Had the same problem. Changing the version @fullcalendar/.. from 5.5.0 to 5.3.1 solved the issue. (Did not try with other version).

**Comment by arshaw** [comment]
If you could try to reproduce this problem in v6, that'd be great. I've added additional debugging templates:
https://fullcalendar.io/reduced-test-cases

**Comment by MikeChuckRoast** [comment]
The problem was resolved for me in 5.6. I'm now on 5.10 and still problem free.

**Comment by arshaw** [comment]
Okay great. Closing
