### ISSUE TITLE
Bug: Events get duplicated multiple times when dropping and updating them from the options object

### ISSUE THREAD

**Issue by johannesjo** [fullcalendar/fullcalendar-angular#357]
Steps to recreate:
1. Check out https://github.com/johannesjo/super-productivity/tree/feat/calendar
2. execute `yarn && ng serve`
3. Create a couple of tasks in the task list view
4. Open the menu and select "Calendar"
5. Start to drag around the tasks in the daily agenda view like a mad man.

All the relevant code is located here:
https://github.com/johannesjo/super-productivity/blob/feat/calendar/src/app/features/calendar/calendar.component.ts

Result:
Events will be duplicated multiple times until the calendar is completely rererendered (by navigating away and then back).

### Is your bug/feature applicable to the core project, without Angular?
I am not sure.

**Comment by acerix** [comment]
Please submit this ticket under Issues with a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/), then link this PR to it.
