### ISSUE TITLE
Events get duplicated  times when dropping and updating them from the options object

### ISSUE THREAD

**Issue by johannesjo** [fullcalendar/fullcalendar-angular#358]
Follow up to: https://github.com/fullcalendar/fullcalendar-angular/issues/357

Steps to recreate:
1. Go to https://codesandbox.io/s/ecstatic-colden-xernn?file=/src/app/app.component.ts
2. Start to drag around the tasks in the daily agenda view like a mad man.

Result:
Events will be duplicated multiple times until the calendar is completely rererendered (by navigating away and then back).

### Is your bug/feature applicable to the core project, without Angular?
I am not sure.

**Comment by acerix** [comment]
Thanks, I can see the issue but I'm not sure it's a bug in the calendar.  It's best if you can provide a more minimal demo,  for example by starting with the example project and only adding the code which causes the bug.  

https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/angular?file=/src/app/app.component.ts

**Comment by johannesjo** [comment]
Here is a little bit more reduced example: 
https://codesandbox.io/s/old-wind-7vdf3?file=/src/app/app.component.ts

Please pay attention to line 62. This is the (only) place where the calendar get's updated and the data passed, does not match with what is displayed.

**Comment by acerix** [comment]
Thanks for the details. I'm not very familiar with how Angular works and was suspicious the issue was related to `setInterval` but this does seem like a bug now.

**Comment by johannesjo** [comment]
@acerix yes, it seems so. Looking at the code for the angular integration my suspicion would be that this is at least partly a problem of fullcalendar itself as the correct options get passed as they should. 

And if I may say so: Additionally the part with `pauseRendering` and `resumeRendering` smells like a race condition looming somewhere :)

**Comment by johannesjo** [comment]
After playing around with it some more I recognized, that this seems (at least also) to be happening while an event is being dragged around and not necessarily when it is dropped.

**Comment by johannesjo** [comment]
Would you accept PRs in case I find the cause of it?

**Comment by shyamal890** [comment]
I am able to reproduce this issue too @acerix

**Comment by arshaw** [comment]
This ticket is superseded by the other ticket you made @johannesjo:
https://github.com/fullcalendar/fullcalendar/issues/6218#issuecomment-1344785330
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

I reopened it and [made a new comment](https://github.com/fullcalendar/fullcalendar/issues/6218#issuecomment-1344785330)
