### ISSUE TITLE
The first letter of the month does not appear in capital letters in the title with the language in Spanish

### ISSUE THREAD

**Issue by fjms** [fullcalendar/fullcalendar-angular#359]
In the monthly view when setting the language in Spanish the title is in lower case, instead of the first letter in capital letters

The techniques for overwriting the css do not work, any advice?

![image](https://user-images.githubusercontent.com/7184125/105182667-9a945380-5b2d-11eb-9ea4-71943a492e04.png)

**Comment by fjms** [comment]
Ok, solved. Although I would not like to use ng-deep

`
:host::ng-deep h2.fc-toolbar-title {
    text-transform: capitalize;
}
`

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
