### ISSUE TITLE
Whitespace between header buttons are rendered as tiny buttons.

### ISSUE THREAD

**Issue by maurice85** [fullcalendar/fullcalendar-angular#365]
Spacing between the buttons in header Toolbar are rendered as captionless buttons instead of spaces. Recreation can be found here: https://codesandbox.io/s/affectionate-bogdan-0yswp

The header toolbar is defined as follows:

`    headerToolbar: {
      left: "prev    ,next today",
      center: "title",
      right: "dayGridMonth,timeGridWeek,timeGridDay,listWeek"
    },`

There are 4 spaces behind `prev` which are all rendered as tiny buttons. According to the [docs](https://fullcalendar.io/docs/headerToolbar) a space after a value should be rendered as a space.

**Comment by acerix** [comment]
The buttons should be separated by a space _or_ by a comma, using both creates a "blank" button in between the two separators.

https://codepen.io/acerix/pen/GRrxJeB?editors=001
