### ISSUE TITLE
Dot markers in ListView mode do not render properly when the borderColor property is set on the event.

### ISSUE THREAD

**Issue by maurice85** [fullcalendar/fullcalendar-angular#366]
Please see my recreation here https://codesandbox.io/s/affectionate-bogdan-0yswp
Click on the List mode button on the right and look at the color of the dot marker of "All-day event".
The dotmarker is black because `borderColor: ` is set to `"#000000"`. This overrides the `red` values of 
`backgroundColor` and `color`. When i remove `borderColor: "#000000"` the dot marker will be displayed as red as it should be. In previous versions i was able to set all three  properties without them interferring with each other. But now borderColor causes
the entire dot marker to become black.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5533
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by maurice85** [comment]
Dear Dylan,

Did you check out my codesandbox example? I already tried adding
eventDisplay: "block". This does nothing for the dot marker in LIST view.
Please check my example here.
https://codesandbox.io/s/affectionate-bogdan-0yswp Also, I am using
the angular connector. Could you reopen the issue please?

Regards,

Maurice

**Comment by acerix** [comment]
In the list view, events are always displayed as "list-item" so it's the same issue as in #5533.  As a workaround, you can override the colors like this:

https://fullcalendar.io/docs/list-view#event-appearance
