### ISSUE TITLE
IE11 Console Error Msg "SCRIPT1053: Const must be initialized" Calendar not rendering

### ISSUE THREAD

**Issue by pford23** [fullcalendar/fullcalendar-angular#367]
### Problem / Bug
The following error is displayed in the console when trying to use the fullcalendar with angular in the IE11.

![error-msg-console-ie11](https://user-images.githubusercontent.com/82590288/115189098-38c09700-a0e6-11eb-9585-36f2b79f1b3e.PNG)

Clicking on the location will bring up the following.

![error-code-section-ie11](https://user-images.githubusercontent.com/82590288/115189244-7b826f00-a0e6-11eb-91d2-ffd6248702c9.PNG)

This code section can be found in the node_modules\@fullcalendar\angular\fesm2015\fullcalendar-angular.js line 36-44

The const in a for-in loop is not supported by IE11 the funny thing is that the example project works in IE11.

### Json FIles

I managed to replicate the problem from my employers project by creating an empty angular project and adding the fullcalendar with the following setup.

**package.json dependecies**

![package-json-deps](https://user-images.githubusercontent.com/82590288/115189715-37439e80-a0e7-11eb-8198-7f070ad1cde6.PNG)

**tsconfig.json**

![tsconfig-json](https://user-images.githubusercontent.com/82590288/115189773-52aea980-a0e7-11eb-9e38-646d22c3a5be.PNG)

The **angular.json** file was not changed and used as generated by the CLI.

**Polyfills.js is identical to the example project polyfill.js**

### Replicate

Create new angular project with the above package.json dependencies and tsconfig.json file.
Add fullcalender to app.component.
Aboce error msg will appear in console in IE11.

### My Thoughts
Is it possible that it may have to do with the angular and Typescript version?
My project uses Angular 9 the example project Angular 10.
Typescript versions are also different my project version 3.8.3 example project version 3.9.7

**Comment by arshaw** [comment]
I discovered there's a way to modify the example project to output more IE-friendly JS (there is no problem with the @fullcalendar/angular package)

https://github.com/fullcalendar/fullcalendar-angular/issues/353#issuecomment-853358184
