### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by shyamal890** [fullcalendar/fullcalendar-angular#369]
Fullcalendar doesn't support Angular 12 can you please check

**Comment by SamuelLeclerc33** [comment]
From what I've seen, the only thing that needs fixing is the peer dependency. If you are able to live with the warning, it works.

**Comment by arshaw** [comment]
@shyamal890 you were right about it being a painless upgrade. I released [v5.7.1](https://github.com/fullcalendar/fullcalendar-angular/releases/tag/v5.7.1) and it has support for Angular 9-12

**Comment by muuvmuuv** [comment]
README still says "...-11" needs to be updated too.
