### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

### ISSUE THREAD

**Issue by victorgt26** [fullcalendar/fullcalendar-angular#374]
### Bug Reports
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

### Feature Requests
In smarthphone (responsive) the select event don´t work, display the next message:

[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

"@fullcalendar/angular": "^5.8.0",
"@fullcalendar/core": "^5.8.0",

<img width="356" alt="Captura de Pantalla 2021-06-27 a la(s) 13 33 33" src="https://user-images.githubusercontent.com/20076727/123555382-6f083b80-d753-11eb-90cd-4e544be6d1e4.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5899
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
