### ISSUE TITLE
Documentation around actually using the license key

### ISSUE THREAD

**Issue by AminZom** [fullcalendar/fullcalendar-angular#378]
Before we purchased the premium license we weren't sure if it was going to be one license for X number of developers or X number of different licenses. Making this known on the site would be very beneficial.

Some documentation around actually incorporating the license key into the application, and where it should exactly go would also be very beneficial to kick things off!

Thank you!

**Comment by acerix** [comment]
It's based on the number of developers, you can find more details here: https://fullcalendar.io/purchase  or contact sales@fullcalendar.io

This explains how to include the license key:

https://fullcalendar.io/docs/premium#free-trial
