### ISSUE TITLE
Securely Injecting License Key Into the Application

### ISSUE THREAD

**Issue by AminZom** [fullcalendar/fullcalendar-angular#381]
Our application is on the cloud and we are attempting to safely inject the premium license key we purchased into the web app without exposing this key to the public. We tried storing this license key in a file on the cloud, and fetching it through our application. This works except the file is exposed to the browser, and anyone could see the license key by using the console.

Any advice on how to inject this license key without exposing it to the public based on other applications you may have seen would be fantastic help for us. Thanks in advance!

**Comment by acerix** [comment]
The license key is not private and needs to be included in the code, there is no need to keep it secure.
