### ISSUE TITLE
Update supported Angular version in docs

### ISSUE THREAD

**Issue by Nickishero** [fullcalendar/fullcalendar-angular#384]
Hey,

https://fullcalendar.io/docs/angular
![afbeelding](https://user-images.githubusercontent.com/37247484/137475367-0a2548e9-3cd3-4e09-be83-c04b3321acaf.png)

Fullcalender docs say Angular 9 support. 

Actual support as of v5.7.1 is Angular 12.
![afbeelding](https://user-images.githubusercontent.com/37247484/137475439-7e40e7c3-4696-4d0d-a2a7-e8f2022a93f7.png)

Sorry for not following the template.

**Comment by arshaw** [comment]
It has been updated to say 9 - 14
https://fullcalendar.io/docs/angular
