### ISSUE TITLE
Upgrade to Angular 13

### ISSUE THREAD

**Issue by zornic84** [fullcalendar/fullcalendar-angular#387]
### Reduced Test Case

You must paste a link to a [REDUCED TEST CASE](https://fullcalendar.io/reduced-test-cases).
If you do not, this issue will automatically be closed.
To prevent this, include the text "not reproducible with a link" (assuming it's true).

### Bug Description

I want to upgrade from Angular12 to Angular13, but I get the following error message when running "npm update":

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: serenity@12.2.0
npm ERR! Found: @angular/common@13.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"9 - 12" from @fullcalendar/angular@5.10.1
npm ERR! node_modules/@fullcalendar/angular
npm ERR!   @fullcalendar/angular@"^5.10.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

### Screenshots

![image](https://user-images.githubusercontent.com/38258137/141432092-4557541d-409c-4826-b5db-df09864f22e0.png)

**Comment by acerix** [comment]
There's a PR for Angular 13 support which may work:

https://github.com/fullcalendar/fullcalendar-angular/pull/386

**Comment by jefbarn** [comment]
From Angular 13:

Processing legacy "View Engine" libraries:
- @fullcalendar/angular [es2015/esm2015] (https://github.com/fullcalendar/fullcalendar-angular.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by blueiceprj** [comment]
Hi,

After updating to angular @angular/cli 13.1.0 getting this ChunkLoadError. But everything is work on with 13.0.4 version.

ChunkLoadError: Loading chunk src_app_main_my-page_courses_calendar_courses-calendar_module_ts-src_app_main_school-course_s-b9f0e3 failed. (error: http://localhost:4200/src_app_main_my-page_courses_calendar_courses-calendar_module_ts-src_app_main_school-course_s-b9f0e3.js)

**Comment by iwnow** [comment]
@blueiceprj the same error

**Comment by Timebutt** [comment]
Hi @blueiceprj this is an issue related with `@angular-devkit/build-angular`, see my comment [here](https://github.com/fullcalendar/fullcalendar-angular/pull/386#issuecomment-993462283) for a possible solution.

**Comment by arshaw** [comment]
I've released @fullcalendar/angular version 5.10.2, which supports angular 13.

Please post issues as other tickets.

For more discussion, [see this thread](https://github.com/fullcalendar/fullcalendar-angular/pull/386#issuecomment-1033225336)
