### ISSUE TITLE
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries.

### ISSUE THREAD

**Issue by Yamesh1994** [fullcalendar/fullcalendar-angular#392]
Angular 13
ng serve
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- @fullcalendar/angular [es2015/esm2015] (git+https://github.com/fullcalendar/fullcalendar-angular.git)

Encourage the library authors to publish an Ivy distribution.

Please update package

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-angular/issues/387
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
