### ISSUE TITLE
Library is not compatible with Ivy

### ISSUE THREAD

**Issue by AlessandroSomma** [fullcalendar/fullcalendar-angular#396]
I installed the latest version of @fullcalendar/angular (5.11.0) in an Angular 13 application.
I have an error building the application using ngc and Webpack.

# Reproduce the error

I have created a repository with a minimal Angular 13 project to reproduce the issue:
https://github.com/AlessandroSomma/fullcalendar-angular-13

Steps to reproduce:
* clone the repository
* run ```npm install```
* run ```npm start``` or ```npm run build```
* see the error

# Details

Error logged:
```
node_modules/@fullcalendar/angular/lib/fullcalendar.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@fullcalendar/angular) which declares FullCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

Use ngcc before building will fix the issue but in my situation it would be difficult to use it because of package manager.
Also using it in the test project a warning is logged: 
```
Processing legacy "View Engine" libraries:
- @fullcalendar/angular [fesm2015/esm2015] (git+https://github.com/fullcalendar/fullcalendar-angular.git)
- @fullcalendar/angular [esm2015/esm2015] (git+https://github.com/fullcalendar/fullcalendar-angular.git)
- @fullcalendar/angular [main/umd] (git+https://github.com/fullcalendar/fullcalendar-angular.git)
Encourage the library authors to publish an Ivy distribution.
```

**Comment by arshaw** [comment]
@AlessandroSomma , would you be so kind as to check if v5.10.2 is doing this as well?

**Comment by AlessandroSomma** [comment]
@arshaw, i try with v5.10.2 and the behavior is the same

**Comment by DeNasti** [comment]
I'm having the same problem (also with v5.10.2 )

**Comment by Timebutt** [comment]
I have an [open PR](https://github.com/fullcalendar/fullcalendar-angular/pull/386) that's been finished and unmerged for months that address this exact issue :/

**Comment by arshaw** [comment]
Release in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
