### ISSUE TITLE
Bug when dropping the event in same date

### ISSUE THREAD

**Issue by donidemolli** [fullcalendar/fullcalendar-angular#401]
When starting to drag an event in the calendar and then dropping it on the same date, the calendar gets in a stuck state. The item remains in a dragging state even though it is dropped, and no error log is shown in the console
Versions:
Angular 13

"@fullcalendar/angular": "^5.11.0",
"@fullcalendar/daygrid": "^5.11.0",
"@fullcalendar/interaction": "^5.11.0",

![ezgif-1-cda08d075e](https://user-images.githubusercontent.com/44557862/170955756-85767ac4-23e6-4aff-b9d1-197c710d0b92.gif)

See the gif!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
