### ISSUE TITLE
"Encourage the library authors to publish an Ivy distribution."

### ISSUE THREAD

**Issue by faizaldong** [fullcalendar/fullcalendar-angular#405]
During the build of a project, angular issues the following message:

` @fullcalendar/angular [es2015/esm2015] (https://github.com/fullcalendar/fullcalendar-angular.git)
Encourage the library authors to publish an Ivy distribution.`

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-angular/issues/396
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
