### ISSUE TITLE
Export ResourceInput in angular

### ISSUE THREAD

**Issue by KeithPoonNS** [fullcalendar/fullcalendar-angular#406]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

### Is your bug/feature applicable to the core project, without Angular?
NO

(Please erase the above text and begin typing. Thanks!)

https://github.com/fullcalendar/fullcalendar/issues/5797

I found the ResourceInput was exported since 5.4.0 in main brance but it seems not exported in angular branch?!
Would it be consider to export in angular?

**Comment by arshaw** [comment]
in v6 (beta) you'll just want to [install the @fullcalendar/resource](https://fullcalendar.io/docs/v6/upgrading-from-v5#peer-dependencies) peer dependency and import it from that.

in v5 (what you're using) you can import it directly from the `@fullcalendar/resource-common` package.
