### ISSUE TITLE
@fullcalendar/angular Not working in angular universal

### ISSUE THREAD

**Issue by CodeIntelli** [fullcalendar/fullcalendar-angular#412]
### Bug Reports

Currently, we are using @fullcalendar/angular v5.6.0 in angular V10.1.17 Node version V14.15.0 and we are going through Angular SSR (Angular Universal). But it's not working properly it goes into Loading State. This Libary working properly in Angular Core but when we tried to fix it into SSR(Server Side Rendering) Using Angular Universal 
This issue will occur while reloading the page.

![new Issue](https://user-images.githubusercontent.com/68110141/187025161-4ac90c2f-021c-4097-8dfc-e10f9cf2fb0c.png)

### Solution We have tried

- we have tried to comment on the whole library from the project at that time this issue will be occurring 
- ![Screenshot 2022-08-27 at 3 15 36 PM](https://user-images.githubusercontent.com/68110141/187024851-83595f1c-e6db-4370-8ebe-265e3b8e71db.png)
- After that, we have tried to execute this part of the code into the browser state but not working on that also it goes into the loading state

### Feature Requests
Can You Please help to replicate it?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
