### ISSUE TITLE
Re-initializing the calendar with events and resources can cause resources to be initially scrolled

### ISSUE THREAD

**Issue by simonbos** [fullcalendar/fullcalendar-angular#413]
See [this CodeSandbox](https://codesandbox.io/s/wizardly-kalam-thotdm?file=/src/app/app.component.ts) for a reproducible example. When initializing events and resources to empty lists and re-initializing them later, this causes resources to be initially scrolled. Some workarounds:
* Initializing resources non-empty (e.g. with a dummy resource: `resources: [{id: '', title: ''}]`).
* Waiting until the resources are re-initialized (and re-rendered) before re-initializing events.

This issue seems closely related to [this one](https://github.com/fullcalendar/fullcalendar/issues/6507) which uses React and `datesSet`.

**Comment by simonbos** [comment]
Note: the first workaround doesn't seem to work in cases where the second resource (of the re-initialized resources) also contains a lot of resources. See [this CodeSandbox](https://codesandbox.io/s/async-wood-7vqw9n?file=/src/app/app.component.ts).

**Comment by arshaw** [comment]
Yes, almost definitely the same issue as
https://github.com/fullcalendar/fullcalendar/issues/6507
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
