### ISSUE TITLE
Full Calendar with month view on the side

### ISSUE THREAD

**Issue by sanjayshingadia** [fullcalendar/fullcalendar-angular#415]
### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

Does you software support this type of view?
![image](https://user-images.githubusercontent.com/115793838/195839215-af948f86-0e1b-4050-9087-f8d1500a611b.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6024
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
