### ISSUE TITLE
TypeError in Angular 14 with v6 beta 2

### ISSUE THREAD

**Issue by TahaAttari** [fullcalendar/fullcalendar-angular#419]
https://stackblitz.com/edit/angular-rxt7ay?file=node_modules/@fullcalendar/angular/full-calendar.component.d.ts

In node_modules/@fullcalendar/angular/full-calendar.component.d.ts you can see a TypeError with Angular 14, it has one extra parameter in the type declaration. This works on Angular 15 with no problems

**Comment by arshaw** [comment]
Thank you for the report @TahaAttari 

Released in [v6.0.0-beta.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.3)
