### ISSUE TITLE
Remove fast-deep-equal library for the lack of ESM support

### ISSUE THREAD

**Issue by bastienmoulia** [fullcalendar/fullcalendar-angular#421]
### Bug Reports
I have the following warning in Angular:

Warning: node_modules\@fullcalendar\angular\fesm2020\fullcalendar-angular.mjs depends on 'fast-deep-equal'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Can you remove this lib (only use [once](https://github.com/fullcalendar/fullcalendar-angular/blob/daa5e7464a097cbe4f95d2d4de174755a424807b/projects/fullcalendar/src/lib/fullcalendar.component.ts#L65)) using another lib or inlining the needed function?

**Comment by bastienmoulia** [comment]
Fixed with https://github.com/fullcalendar/fullcalendar-angular/commit/1eee15937322d73b3482df23e50bc14654223728

**Comment by arshaw** [comment]
Yes, thank you for the report @bastienmoulia 

In [v6.0.0-beta.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0-beta.3)

**Comment by arshaw** [comment]
Release in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)
