### ISSUE TITLE
ViewAPI - View Object is missing "type" property string with name of view.

### ISSUE THREAD

**Issue by ganySA** [fullcalendar/fullcalendar-angular#422]
View API view object is missing the 'type' property - as documented by the docs.

as per docs:

**type
Name of one of the available views (a string).**

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by ganySA** [comment]
Is there a working version 6 playground? See only 5.

not trying to be difficult but this really doesn’t need much to reproduce - it’s a missing property on a documented object. Take a look at viewapi “type” is missing.

**Comment by oliverguenther** [comment]
Happens to us during the upgrade from fullcalendar v5.10 to v6.beta3. We have a side effect that when dates set, we keep a certain state paramter of the view. We use `dates.view.type` in that.

I've boiled it down to this stackblitz: https://stackblitz.com/edit/angular-ivy-xzp8su?file=src/app/app.component.ts

**Comment by ganySA** [comment]
Just checking if this one is still open - i saw version 6 released but this still looks problematic.

**Comment by acerix** [comment]
This is not specific to Angular and was reported in the main repo so I'll move to that issue:

https://github.com/fullcalendar/fullcalendar/issues/7056
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
