### ISSUE TITLE
schedulerLicenseKey is not assignable to type CalendarOptions

### ISSUE THREAD

**Issue by Snoppi-Wizard** [fullcalendar/fullcalendar-angular#425]
I use Angular 15.0.3 with FullCalendar 6.0.0-beta4.
Now it seems that the property 'schedulerLicenseKey' is not valid any more (my IDE is complaining).
Where do I have to enter the key now?

**Comment by arshaw** [comment]
You'll need to install new peerDependency: `@fullcalendar/resource`

https://fullcalendar.io/docs/v6/upgrading-from-v5#peer-dependencies

I might need to make this clearer

**Comment by Snoppi-Wizard** [comment]
This works for me. But I do not use the resource plugin at all, so I thought I do not have to install it.
