### ISSUE TITLE
Missing property in ViewApi interface

### ISSUE THREAD

**Issue by strechea** [fullcalendar/fullcalendar-angular#427]
In the documentation https://fullcalendar.io/docs/view-object
In the code 
![image](https://user-images.githubusercontent.com/82370135/207853551-20950198-6f3d-4981-a47c-19bcff7b7fd5.png)

The property "type" is missing, although based on the information of the documentation it should be there.

Edit: In version 5.11 it was there:
![image](https://user-images.githubusercontent.com/82370135/207890192-64c77645-0b9c-4cbe-ad39-f32628b97e2e.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/7056
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
